### ISSUE TITLE
no docs

### ISSUE THREAD

**Issue by mikeserv** [LongSoft/UEFITool#1]
This tool and applications like it are, in my opinion, vital gateways to user-owned and hack-friendly firmware. It can do no one any good, however, if it is undocumented. I would like to assist in this effort if you'll allow it, but I'll first need to understand how it works. 

A simple README with build instructions is the first step, I think. I will draw one up, and possibly a POSIX shell build script if you will guide me.

Seriously, thank you for putting in the effort to create this tool.

( An example of just how wordy I can get: http://www.coreboot.org/pipermail/coreboot/2013-October/076442.html )

**Comment by NikolajSchlej** [comment]
Wrote a simple readme with breif build instructions, links to another projects using UEFITool's engine, introduction to UI and features and known issues. Time to close this issue, I think.
