### ISSUE TITLE
Cannot decompress LZMA section of UEFI

### ISSUE THREAD

**Issue by ApertureSecurity** [LongSoft/UEFITool#102]
I think I am missing something very simple that is probably trivial.

If this is the case, then I am sorry . )

I am trying to extract part of a UEFI Firmware and I see the option to decompress, but I cannot do this( it's grayed out). Is there a tool that I am missing to do this? 

Thank you!

![capture](https://user-images.githubusercontent.com/4926248/34357404-81409a1c-ea4f-11e7-9087-c8fc943a2b19.PNG)

**Comment by NikolajSchlej** [comment]
It's already decompressed in the tree, just extract body of this section and you'll get decompressed data.

**Comment by ApertureSecurity** [comment]
I understand. I will close this then .
