### ISSUE TITLE
Intel Flash Descriptor official version

### ISSUE THREAD

**Issue by platomav** [LongSoft/UEFITool#104]
Intel has added an official FD version at new SPI images. It is a dword at the, previously reserved, FLMAP3 (FDBAR + 0x20). The first 11 bits are the Major, the next 7 Minor and the other 14 Reserved. For example:

![capture](https://user-images.githubusercontent.com/11527726/35195346-d8578f92-feca-11e7-8467-89c4adb0097a.PNG)

0x00002000 LE --> 0x00200000 BE --> 00000000001 0000000 00000000000000b --> v1.0

Since FLMAP3 used to be reserved, UEFITool can keep its current detection when 0xFFFFFFFF or otherwise use the official tag. Note that Intel's v1.0 will be equivalent to UEFITool's unofficial v3 (not v2).

**Comment by vit9696** [comment]
Thanks for the research. Actually I managed to miss it even though I searched through the issue tracker. Both master and new_engine should be good at handling the new images now. Closing as resolved.
