### ISSUE TITLE
Nothing to patch...

### ISSUE THREAD

**Issue by maxhartung** [LongSoft/UEFITool#106]
These Gigabyte guys made a BIOS file that's rubbish to say at least. If I want to unlock secret menus I can't because the program crashes (AMIBCP) if I want to patch it using UEFIPatch says nothing to patch. 

What's wrong ?

Here is the BIOS file:

http://download.gigabyte.eu/FileList/BIOS/mb_bios_ga-b85m-d2v_f4.zip

It's a gigabyte board GA-B85M-D2V.

**Comment by NikolajSchlej** [comment]
Nothing is wrong. UEFIPatch is a generic tool and the only patchset provided as example is 0xE2 register unlock which has nothing to do with secret menus.
