### ISSUE TITLE
Unable to make UEFIDump due to existed folder name

### ISSUE THREAD

**Issue by dbpalan** [LongSoft/UEFITool#107]
Build UEFIDump (from new engine source) for non-QT method gives linking error:

> $cd UEFITool-new-engine
> $cmake UEFIDump
> $make
> Scanning dependencies of target UEFIDump
> [  4%] Building CXX object CMakeFiles/UEFIDump.dir/uefidump_main.o
> [  9%] Building CXX object CMakeFiles/UEFIDump.dir/uefidump.o
> [ 13%] Building CXX object CMakeFiles/UEFIDump.dir/common/guiddatabase.o
> [ 18%] Building CXX object CMakeFiles/UEFIDump.dir/common/types.o
> [ 22%] Building CXX object CMakeFiles/UEFIDump.dir/common/descriptor.o
> [ 27%] Building CXX object CMakeFiles/UEFIDump.dir/common/ffs.o
> [ 31%] Building CXX object CMakeFiles/UEFIDump.dir/common/nvram.o
> [ 36%] Building CXX object CMakeFiles/UEFIDump.dir/common/nvramparser.o
> [ 40%] Building CXX object CMakeFiles/UEFIDump.dir/common/ffsparser.o
> [ 45%] Building CXX object CMakeFiles/UEFIDump.dir/common/ffsreport.o
> [ 50%] Building CXX object CMakeFiles/UEFIDump.dir/common/peimage.o
> [ 54%] Building CXX object CMakeFiles/UEFIDump.dir/common/treeitem.o
> [ 59%] Building CXX object CMakeFiles/UEFIDump.dir/common/treemodel.o
> [ 63%] Building CXX object CMakeFiles/UEFIDump.dir/common/utility.o
> [ 68%] Building C object CMakeFiles/UEFIDump.dir/common/LZMA/LzmaDecompress.o
> [ 72%] Building C object CMakeFiles/UEFIDump.dir/common/LZMA/SDK/C/LzmaDec.o
> [ 77%] Building C object CMakeFiles/UEFIDump.dir/common/Tiano/EfiTianoDecompress.o
> [ 81%] Building CXX object CMakeFiles/UEFIDump.dir/common/ustring.o
> [ 86%] Building C object CMakeFiles/UEFIDump.dir/common/sha256.o
> [ 90%] Building C object CMakeFiles/UEFIDump.dir/common/bstrlib/bstrlib.o
> [ 95%] Building CXX object CMakeFiles/UEFIDump.dir/common/bstrlib/bstrwrap.o
> [100%] Linking CXX executable UEFIDump
> /usr/bin/ld: cannot open output file UEFIDump: Is a directory
> collect2: error: ld returned 1 exit status
> CMakeFiles/UEFIDump.dir/build.make:614: recipe for target 'UEFIDump' failed
> make[2]: *** [UEFIDump] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/UEFIDump.dir/all' failed
> make[1]: *** [CMakeFiles/UEFIDump.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2

Workaround by rename UEFIDump folder to whatever else:
> $cd UEFITool-new-engine
> $mv UEFIDump UEFIDumpDir
> $cmake UEFIDumpDir
> $make

**Comment by NikolajSchlej** [comment]
It's better to create cmake intermediate files outside of source repo or in 'build. folder, which is added .gitignore already.
