### ISSUE TITLE
Two NVRAM sections

### ISSUE THREAD

**Issue by c0d3z3r0** [LongSoft/UEFITool#110]
While doing some modifications to my UEFI image I noticed that I have two NVRAM sections.
I thought that must be wrong so I reflashed a virgin UEFI image with an empty NVRAM section only containing StdDefaults via flashrom/SPI. After rebooting the machine some times I read the image back and checked it in UEFITool. Again, there was an additional NVRAM section with identical GUID but two different "State"s (0xF0 vs. 0xE0, virgin image was 0xF8).

Any ideas what is going on here?

Virgin UEFI image:
![screenshot_2018-02-13_20-37-53](https://user-images.githubusercontent.com/6205797/36169916-f8971d50-10fd-11e8-96c1-7dc0f0eb0fb6.png)

Two NVRAM Sections:
![screenshot_2018-02-13_20-37-19](https://user-images.githubusercontent.com/6205797/36169915-f87eab26-10fd-11e8-8eed-1655230299ec.png)
![screenshot_2018-02-13_20-38-20](https://user-images.githubusercontent.com/6205797/36169917-f8b62cc2-10fd-11e8-9114-470db74853ff.png)

**Comment by c0d3z3r0** [comment]
Ah, looks like I should have waited until the system restarted three times after first power on.
Powering off too early seems to interrupt a setup process... Now there is only one section.

**Comment by NikolajSchlej** [comment]
The second section is used as backups storage during updates, or as a working storage if the main one fails too hard to be restore by garbage collection. It's ok to have 2 of them.
