### ISSUE TITLE
Could you create an Appimage of this for Linux?

### ISSUE THREAD

**Issue by older-pack** [LongSoft/UEFITool#124]
UEFITool and FD44Editor are great tools.
Could you create [Appimage](https://appimage.org) versions for Linux?
(I'm not able to compile my own Linux app)
Thank you.

(Same request on [FD44Editor](https://github.com/LongSoft/FD44Editor/issues/5) too.)

**Comment by edmalho** [comment]
+1

**Comment by vit9696** [comment]
Hello, recent master and new_engine got Linux binary deployment, so precompiled tools will be ready for x86_64 Ubuntu 14.04 or newer (compatible with Ubuntu 18.04, Debian 9, and supposedly many other distributions). If you want an AppImage in particular you may submit a pull-request.
