### ISSUE TITLE
Replace FV as-is doesn't preserve input FV alignments

### ISSUE THREAD

**Issue by osresearch** [LongSoft/UEFITool#125]
When a FV is replaced using the "Replace As-Is" option, the input FV is parsed and compacted, which can lead to errors on some systems with non-relocatable binaries.  As-Is seems like it should not modify the input file at all and should just copy the bytes into the output.

As a workaround I used `dd` to replace the volume: 
```
dd if=pei.fv of=test.rom conv=notrunc bs=$[0x10000] seek=$[0xF0]
```

**Comment by vit9696** [comment]
Use `Do not rebuild` in 0.23.0 (or 0.23.1).
