### ISSUE TITLE
UEFI volumes not found in XPS 15 9575 2in1

### ISSUE THREAD

**Issue by shiecldk** [LongSoft/UEFITool#127]
Hello,

UEFITool shows “UEFI volumes not found" (in both Windows and Mac version)

Bios of XPS 15 9575:
https://app.box.com/s/kslp6tchn0q89mnc170h1avie2vr9nav

Can someone help me to fix it? Thanks

**Comment by skochinsky** [comment]
This an executable firmware updater containing the image in encrypted or compressed form, so UEFITool can't handle it.
