### ISSUE TITLE
GZIP is not Supported

### ISSUE THREAD

**Issue by dylangerdaly** [LongSoft/UEFITool#138]
Hello,

It appears LZMA is currently only supported, I'm dealing with images that have FV's within the root FV.

Upon trying to extract the body out I get a compression error, this is because the FV is compressed with GZIP, not LZMA.

_I think_

Nevertheless, great tool 👍

**Comment by vit9696** [comment]
Hi, could you please attach the firmware that uses GZIP compression?

**Comment by dylangerdaly** [comment]
I've figured this out, it was a vendor specific issue, thank you and sorry for raising unnecessary issues.
