### ISSUE TITLE
Uefi could not turn on my bios warning: invalid uefi volume;

### ISSUE THREAD

**Issue by 947614975** [LongSoft/UEFITool#139]
My computer manufacturer restricted the BIOS, which prevented me from booting Android and unlocking TDP.
Uefitool could not turn on my bios warning: invalid uefi volume;
factory bios; it doesn't look like a problem, but there are no options
my modified setup configuration BIOS via AMI BCP,But flash into the system doesn't change ; even if I turn off VT it No effect; but my logo can be modified through changlog

**Comment by 947614975** [comment]
<img width="411" alt="qq 20180718015132" src="https://user-images.githubusercontent.com/41341767/42836569-fee77b10-8a2d-11e8-8a06-031814bfe80a.png">

**Comment by 947614975** [comment]
![Uploading 20180717_010933.jpg…]()

**Comment by 947614975** [comment]
![20180717_010933_](https://user-images.githubusercontent.com/41341767/42836883-e8fa973c-8a2e-11e8-979a-f3250dbe7ad9.jpg)

**Comment by vit9696** [comment]
Could you upload your BIOS dump please? Looks like you forgot :)

**Comment by 947614975** [comment]
GITHU Bwarning：Something went really wrong, and we can’t process that file.  
So I couldn't get my last my BIOS
So I used mega.
this is factory bios
https://mega.nz/#!bNViUKQK!eHfSU55JTG5CRdO7ZITYkwNnOUdvAmgn3ilqtw47l7I
this is Modificationsetup configuration
https://mega.nz/#!TJEy0QaY!wW-3hdvxEfW8mMTYD8mq240mxGh8UCQ2SoZyDL0IR-E

Thanks

**Comment by vit9696** [comment]
Your roms appear to have intersecting regions. Here is a fixed one:
[afuwin_20180714050901_fixed.rom.zip](https://github.com/LongSoft/UEFITool/files/2203069/afuwin_20180714050901_fixed.rom.zip)

**Comment by LSSoniX** [comment]
@vit9696 
Приветствую. Вся проблема в использовнии AMIBCP. Для Аптио 5 данная софтина только портит биосы, уже проверено многократно, одни кирпичи получались. Советуем держаться от данной утилиты поодальше

**Comment by vit9696** [comment]
Привет, да, знаю, надо работать над NE.

**Comment by platomav** [comment]
As @LSSoniX said, the SPI regions gets corrupted due to a buggy AMIBCP version. Thus, this is not an UEFITool issue. Unlocking the TDP via IFR or similar is also not UEFITool related. At best, it is modding related.
