### ISSUE TITLE
Rebuild PEI module creates invalid TE

### ISSUE THREAD

**Issue by lasalvavida** [LongSoft/UEFITool#140]
Firmware for [SuperMicro A2SDi-2C-HLN4F](https://www.supermicro.com/products/motherboard/atom/A2SDi-2C-HLN4F.cfm) (can be downloaded from this page under "update your bios")

The PEI modules contain TE images. Performing a rebuild operation on any of them without making any other changes will create an invalid TE and the firmware will no longer boot properly, where I would expect the rebuild operation to make no changes.

Attached is an example using ProjectPei (B873591A-E633-4CFD-99F7-48D13207D107)

[pei-modules.zip](https://github.com/LongSoft/UEFITool/files/2207167/pei-modules.zip)

![screenshot from 2018-07-18 15 55 14](https://user-images.githubusercontent.com/2489570/42904442-18e39d58-8aa3-11e8-8ac3-de1a9274d63e.png)

**Comment by lasalvavida** [comment]
Uncommenting the code here https://github.com/LongSoft/UEFITool/blob/master/ffsengine.cpp#L4012 (and adding a close brace) resolves this issue.

Looks like there are no plans to fix this in the old engine, but figure it may be useful for somebody with the same issue.

**Comment by dsanke** [comment]
I found the same problem when modifying modules that the volume coutains some pad-file and PEI modules . It will remove some ( not all ) empty pad-file and cause the address in PEI become incorrect .

**Comment by NikolajSchlej** [comment]
I'm mass-closing all issues that are specific to the old engine, because no further work is planned to be done on it, and all the bugs that are present there are to remain there forever. The original engine had a good run, but it needs to go in peace.
