### ISSUE TITLE
"mCode FFS: reconstructVolume: root volume can't be grown"

### ISSUE THREAD

**Issue by pandavova** [LongSoft/UEFITool#143]
Hey, i wanted to update the microcodes with UBU on my gigabyte-h97-d3h bios, but it wont work.
![cmd_02 09 2018_13-21-16](https://user-images.githubusercontent.com/9296158/44955412-18028f00-aeb3-11e8-99a8-0523f0307719.png)
Am i doing something wrong/ how could i fix this problem? i already tried it with every version of the bios.
Here are the Bios Files (click on "BIOS(+5)"): https://www.gigabyte.com/de/Motherboard/GA-H97-D3H-rev-10#support-dl

**Comment by vit9696** [comment]
Not a bug of UEFITool, as your bios does not have enough space.
