### ISSUE TITLE
Проблемы с консольными утилитами NE A52

### ISSUE THREAD

**Issue by LSSoniX** [LongSoft/UEFITool#147]
Всем доброго здравия.

Протестил UEFIFind и UEFIExtract - NE A52
Обе утилиты сломаны. :(
Сравнение с NE A51.
UEFIFind - ничего не находит, пример

@echo Find Capsule Header A51
UEFIFind_NE51.exe Z87-PLUS-ASUS-2103.CAP header count 8BA63C4A2377FB48803D578CC1FEC44D
Результат: 1

@echo Find Capsule Header A52
UEFIFind_NE52.exe Z87-PLUS-ASUS-2103.CAP header count 8BA63C4A2377FB48803D578CC1FEC44D
Резултата нет.

@echo Find IRST A51
UEFIFind_NE51.exe Z87-PLUS-ASUS-2103.CAP body list 49006E00740065006C00280052002900200052005300540020003.00
Результат: 91B4D9C1-141C-4824-8D02-3C298E36EB3F
@echo Find IRST A52
UEFIFind_NE52.exe Z87-PLUS-ASUS-2103.CAP body list 49006E00740065006C00280052002900200052005300540020003.00
Результата нет
Остальные аргументы аналогичны.

UEFIExttract NE 52
@echo Extract EFI IRST
UEFIExtract Z87-PLUS-ASUS-2103.CAP 91B4D9C1-141C-4824-8D02-3C298E36EB3F -o TEST -m body -t 10
Результат получено только 3 вложенных папки 'TEST'

Файлы для тестов https://cloud.mail.ru/public/64Lc/8vuiN6yVU

Спасибо

**Comment by LSSoniX** [comment]
UEFIExtract NE A52 дополнение.
Я проверил разные варианты с аргументами <-o -m -t>/
Если указан основной GUID, то в лучшем случае извлекается секция UI или ее содержимое, если оно есть, в остальном пустые вложенные папки.
Но если извлекать SubGUID (FreeForm),
uefiextract ROG-MAXIMUS-X-APEX-ASUS-1602.CAP 380B6B4F-1454-41F2-A6D3-61D1333E8CB4 -o TEST -m body -t 18
то всё извлекается корректно, в различных вариантах

**Comment by vit9696** [comment]
Привет, поправил, проверяй.

**Comment by LSSoniX** [comment]
@vit9696 
Посмотри пожалуйста заодно и микоды
UEFIExtract Z87-PLUS-ASUS-2103.CAP 17088572-377F-44EF-8F4E-B09FFF46A070 -o TEST -m file
В бивисе их 3 FFS, извлекается как body и явно последний, а не пвый, который "пустышка".

**Comment by vit9696** [comment]
Должно работать. Если что-то забыл — пиши сюда. Но если в целом более-менее, то я склонен выпустить A52, а остальное потом.

**Comment by LSSoniX** [comment]
Увы. :( Исправилось одно, но сломалось другое.
Я подготовлю тебе архив с файлами, скриптом и описанием, что так и не так и скину в ближайшее время, а то мне немного трудно писать.
PS Спасибо, что находишь время на такого зануду как я. :)

**Comment by LSSoniX** [comment]
Забыл сказать, в предпоследней версии от 9 вечера, был очень хороший глюк.
uefiextract bios.bin A062CF1F-8473-4AA3-8793-600BC4FFE9A8 -o CSM -m body
извлекался полный FFS, но без компрессии! Я уже обрадовался и обломался , что этот глюк потом пропал, :)

**Comment by vit9696** [comment]
Залил файлик с фиксом первых двух кейсов. Третий тебе придётся объяснить, как ты такой файл получил. Я взял UEFITool и вытащил file/body, у меня совпало с результатом UEFIExtract. Возможно неверная последовательность действий.

**Comment by vit9696** [comment]
По первому, там тип секции надо указывать, чтобы верные файлы извлекались, разве нет? Если поиском по GUID пройтись в UEFITool, то те же 15 вхождений и будут указаны. Я насколько помню, ранее было требование, чтобы при экстракте GUID матчил не только file guid, но и subguid.

По поводу extract uncompressed, наверное, отдельный багрепорт надо писать. Это скорее запрос фичи.

**Comment by LSSoniX** [comment]
Для <-m body -t xx> да, но для <-m file> тип секций никогда не указывали ранее, извлекаем файл как есть, а не части. А получается, что вытаскиваем целые FFS как есть, но их количество рано содержимому.
Сравни результаты к примеру для GUID 1708 в А51 и текущим.
'uefiextract $a5_bios 17088572-377F-44EF-8F4E-B09FFF46A070 -o mCode -m file'
А А51 мы получим 3 найденных и извлеченных FFS, а в текущей сборке 15 FFS.

Фича uncompressed уже давно в менюшке УТ висит, я думал, что она в проработке и не являлась багом. Поэтому и ждал ее реализации сидя ровно на пятой точке. :)

**Comment by vit9696** [comment]
Понимание бага пришло с распаковкой файла, постараюсь заняться исправлением на следующей неделе.

Касательно uncompressed — там в UEFITool старой были проблемы, из-за которых его в новой версии вроде как не написали. Так что это отдельная фича, в детали которой и причины "непереноса" мне ещё надо будет вникнуть. Оформляй как отдельный баг, постараюсь заняться на досуге.

**Comment by LSSoniX** [comment]
Хорошо, спасибо. Погоняю еще может чего найду.

Да? Странно, я в старом УТ как то проблем с извлечением сжатых body не замечал, до сих пор юзаю на разных файлах. Очень удобно получить содержимое одним файлом в не сжатом виде.
Хорошо. Попозже запостю по uncompкessed в новом УТ.

**Comment by LSSoniX** [comment]
Всем доброго здравия.

По поводу <-o folder>.
Можно прикрутить "костыль"? Если указанная папка естьь, но она не пуста, то выход с ошибкой, но если папка пуста то либо пересоздать ее либо извлекать в нее.
На данный момент, даже если папка пуста то выход с ошибкой.
Так же прогнал несколько вариантов образования этой папки.
Если указан не существующий GUID - папка не создается код ошибки не 0
GUID найден, но не ошибка в <-m> - пакпка не создается, код ошибки не 0
GUID еайден, <-m> корректно, <-t> не корректен, - папка создается пустой и код ошибки 0. - думаю,, что это не правильно.

Так же очень не хватает #150 , чтобы избавится от Мумутула. :(

Спасибо.

**Comment by vit9696** [comment]
Так, проблему с дубликатами файлов при разжатии я исправил. Сначала был загруз, а потом я банально о ней забыл.

В случае с пустой папкой такая хотелка не реализуема, так как есть проблема с детектом. Считать ли пустой папку, в которой есть только скрытый .DS_Store файл или thumbs.db. Даже если считать, то сделать это кроссплатформенно та ещё задача.

Насчёт кода ошибки 0 и создание пустой папки — ошибка, да, но нужен пример.

**Comment by LSSoniX** [comment]
@vit9696 
А! Понял я эту защиту от "дурака". Действительно если пользователь по ошибке укажет какую либо рабочую папку, а в ней будут скрытые или другие рабочие файлы, то будет  конфуз. :)

А примеры по появлению пустой папки с ошибочным заданием аргумента <-t> и кодом выхода 0 я чуть позже опишу. Как раз проверю последнюю сборку.
