### ISSUE TITLE
UEFITool NE - Extract <file|body> uncompressed

### ISSUE THREAD

**Issue by LSSoniX** [LongSoft/UEFITool#150]
Всем доброго здравия!

Есть такая потребность извлекать FFS или тело, если есть сжатие, в расжатом виде, при этом сохраняя исходную структуру.
На данный момент, чтобы извлечь, к примеру весь сжатый FFS как есть с расжатием приходится использовать ММТool
![scr1](https://user-images.githubusercontent.com/20858707/48307954-65614380-e569-11e8-82d0-d437f148df3b.jpg)
или коммандой
'mmtiool bios.bin /e <GUID> <outfile>'
что конечно не доступно для многих работающих не еа ==на Windows. Да и ММТ мсеет свои не достатки.

 В UEFITool версии 0.25.1 и предверсий, есть возможность извлекать Тело со всем сожержимым как есть, но без сжатия. Достаточно встать на секцтю Compessed м выбратиь ПКМ "Extract body"
![scr2](https://user-images.githubusercontent.com/20858707/48308038-99d5ff00-e56b-11e8-8b17-0d3932957cb0.jpg)
В результате мы получим файл со всем содержимым сжатой секции, но в васжатом виде.

В UEFITool NE ни того ни другого сделать не возможно.

Спасибо.

**Comment by NikolajSchlej** [comment]
Fixed in A60, will be released soon.
