### ISSUE TITLE
UEFIExtract producing duplicates of extracted files

### ISSUE THREAD

**Issue by vit9696** [LongSoft/UEFITool#152]
Версии отображаются, тут всё нормально, просто когда начинаем очередные сборки тестить, то путаница иногда возникает какой файл был какой есть и тп.
Как я сказал это не критично. При следующмх тестах будц просто по пкпкам раскилывать, так оно проще будет.

Кстати плодёж файлов не совсем убрался. Вот выловил сегодня.
https://cloud.mail.ru/public/64Lc/8vuiN6yVU
`uefiextract bios.bin DE3E049C-A218-4891-8658-5FC0FA84C788 -o test - m file`
в бивисе с такмс GUID файл 1, но на выходе 3 FFS, как обычно по количеству секций

_Originally posted by @LSSoniX in https://github.com/LongSoft/UEFITool/issues/145#issuecomment-439678362_

**Comment by vit9696** [comment]
@LSSoniX, исправлено в последнем коммите.

**Comment by LSSoniX** [comment]
@vit9696 
Спасибо. Буду тестить.

**Comment by LSSoniX** [comment]
@vit9696 
Извини, что долго. По моим делам всё работает без излишек.
