### ISSUE TITLE
findNextStore: VSS store candidate has invalid size FFFFFFFFh

### ISSUE THREAD

**Issue by gingerluo** [LongSoft/UEFITool#155]
Hello,

I'm using A53 to parse one of my HP G42-480TX laptop 1484F37.fd file, while it shows below issue:

**parseVolumeNonUefiData: non-UEFI data found in volume's free space
findNextStore: VSS store candidate at offset D0048h skipped, has invalid size FFFFFFFFh**

BTW, I downloaded those from HP website, but there are 3 FD files, do you happen to know which is the oen I need to proceed? (I extracted those from the exe file HP gave me on my Serial No.)

I actually want to extract raw bin data and write to BIOS EEPROM using a programmer. Is this the right tool to do it?

Thanks soooo much!

[g42_480xt_bios.zip](https://github.com/LongSoft/UEFITool/files/2707274/g42_480xt_bios.zip)

**Comment by skochinsky** [comment]
This is somewhat offtopic but you should dump the current flash and compare the size. Either 21484F37.fd or 1484F37.fd should work if flashed at the end of the chip.  `1425F37.fd` seems to have extra 0x80000 bytes at the start (possibly EC firmware), and then the Firmware descriptor magic:

```
0000080000: FF FF FF FF FF FF FF FF │ FF FF FF FF FF FF FF FF
0000080010: 5A A5 F0 0F 02 00 04 02 │ 06 02 10 10 20 00 00 00
0000080020: 1B 00 30 09 00 00 00 00 │ 00 00 00 00 FF FF FF FF

```
so if you cut off that header it should match the chip size (0x400000 bytes).

**Comment by gingerluo** [comment]
> 
> 
> This is somewhat offtopic but you should dump the current flash and compare the size. Either 21484F37.fd or 1484F37.fd should work if flashed at the end of the chip. `1425F37.fd` seems to have extra 0x80000 bytes at the start (possibly EC firmware), and then the Firmware descriptor magic:
> 
> ```
> 0000080000: FF FF FF FF FF FF FF FF │ FF FF FF FF FF FF FF FF
> 0000080010: 5A A5 F0 0F 02 00 04 02 │ 06 02 10 10 20 00 00 00
> 0000080020: 1B 00 30 09 00 00 00 00 │ 00 00 00 00 FF FF FF FF
> ```
> 
> so if you cut off that header it should match the chip size (0x400000 bytes).

Igor, 

Thanks for the info.
Sorry forgot to mention, my previous chip (Winbond W25X40) is corrupted and can't be read out to compare, it's a 512KBytes flash (0x200000).
If the magic is "5A A5 F0 0F", why ONLY 1425F37.fd contains it while 21484F37.fd or 1484F37.fd does not?
Given my flash is 512KB, Not sure why any of those files (1024KB and 2048KB) are larger than it?

**Comment by skochinsky** [comment]
I really doubt that a UEFI BIOS can fit into 512KB, better double-check the chip identification. After cutting off the header and loading it into UEFITool we can check the supported chip list in the descriptor region:

> Flash chips in VSCC table:
> C22016 (Macronix MX25U16)
> EF3016 (Winbond W25X32)
> EF4016 (Winbond W25Q32)
> 1C3116 (EON EN25F32)
> 

`5A A5 F0 0F` is the magic of the full flash image (descriptor + ME + BIOS), while the other two files contain probably just the BIOS region (which is always at the end of the flash), or possibly EC+BIOS for configurations without ME.

**Comment by gingerluo** [comment]
> B

Igor,

It's truly W25X40.., is there any similar "magic word" for BIOS only? so I can locate real BIOS section in those FD files..

**Comment by gingerluo** [comment]
> 
> 
> I really doubt that a UEFI BIOS can fit into 512KB, better double-check the chip identification. After cutting off the header and loading it into UEFITool we can check the supported chip list in the descriptor region:
> 
> > Flash chips in VSCC table:
> > C22016 (Macronix MX25U16)
> > EF3016 (Winbond W25X32)
> > EF4016 (Winbond W25Q32)
> > 1C3116 (EON EN25F32)
> 
> `5A A5 F0 0F` is the magic of the full flash image (descriptor + ME + BIOS), while the other two files contain probably just the BIOS region (which is always at the end of the flash), or possibly EC+BIOS for configurations without ME.

Igor,

It's truly W25X40.., is there any similar "magic word" for BIOS only? so I can locate real BIOS section in those FD files..

**Comment by vit9696** [comment]
These messages are just warnings and can be safely ignored. As of chip size, I believe Igor is right, yet in either case this is outside of the UEFITool scope.

**Comment by gingerluo** [comment]
Thanks All!
