### ISSUE TITLE
Support old Aptio 4 / IV for X58

### ISSUE THREAD

**Issue by ajuiJM28** [LongSoft/UEFITool#160]
Hi!
First, thanks for UEFITool, it's very useful!

However, I'm trying to edit some old X58 bios ( I think it's Aptio 4 based ) with the latest version of UEFITool ( A54 alpha ) and does not seem able to parse correctly the partitions. 

[MSI X58M](https://bit.ly/2MpbBGy)

![uefitool-msi-x58m-bios](https://user-images.githubusercontent.com/43304195/51492429-b67f8600-1da9-11e9-9bc2-ab17a5625e44.jpg)

[Asus Rampage II Gene](https://bit.ly/2HrrDAY)

![asus-rampageiigene-bios](https://user-images.githubusercontent.com/43304195/51492435-c008ee00-1da9-11e9-9bce-6e774f4e9401.jpg)

Tried also with the old-engine-based 0.26.0, but it just shows an error dialog "UEFI Volumes not found" when I try to open the bios file.

![uefitool-026-x58m](https://user-images.githubusercontent.com/43304195/51493167-59d19a80-1dac-11e9-8edb-f1d85014fe75.jpg)

Thanks.

**Comment by vit9696** [comment]
Hi, this is not a UEFI firmware. It is most likely AMIBIOS8, which you could try to open with MMTool 3.
