### ISSUE TITLE
Can I use this to modify the values of hidden BIOS options?

### ISSUE THREAD

**Issue by Lord-Kamina** [LongSoft/UEFITool#166]
So, I'd like to patch the CFG Lock on my board (a Gigabyte Z370); the KabyLake sInit patch from patches.txt matches and is applied but apparently not enough to unlock the registers. I don't know what else should I by looking for.

Would it be possible, alternatively to change the default value of the CFG Lock? (or make it visible so I can change it in the UI)? If so, how should I go about that? What should I look for? I tried changing one byte in the PE32 image around where it says 

```
0x37500 		One Of: CFG Lock, VarStoreInfo (VarOffset/VarName): 0x5A4, VarStore: 0x1, QuestionId: 0x2BC, Size: 1, Min: 0x0, Max 0x1, Step: 0x0 {05 91 FF 09 00 0A BC 02 01 00 A4 05 10 10 00 01 00}
0x37511 			One Of Option: Disabled, Value (8 bit): 0x0 {09 07 04 00 00 00 00}
0x37518 			One Of Option: Enabled, Value (8 bit): 0x1 (default) {09 07 03 00 30 00 01}
```

The third from last byte equals the "default" marker, I tried changing them but didn't observe any actual change (maybe that is purely cosmetic?)

**Comment by vit9696** [comment]
It is reasonably hard to diagnose the issue from the provided data, and in either case it is pretty much out of the scope of UEFITool bugtracker.

Currently GIGABYTE provides BIOS variants with CFG Lock visible on request. Contact them at https://esupport.gigabyte.com.

Another option is to update the option via directly in NVRAM: https://github.com/acidanthera/AptioFixPkg#verifymsre2
