### ISSUE TITLE
UI for selecting fonts

### ISSUE THREAD

**Issue by KingBonecrusher** [LongSoft/UEFITool#185]
It there any way to change the font size under linux/debian of the qhex window and firmware tree window? The main menu font is ok, but the rest is too tiny. I tried to edit:

**qhexedit2/qhexedit.cpp**
`setFont(QFont("Mono", 22));`

But no difference....

**Comment by NikolajSchlej** [comment]
Try editing the configuration file created by UEFITool after first run, and send the font name and size there.
https://github.com/LongSoft/UEFITool/blob/new_engine/UEFITool/uefitool.cpp#L907
For Linux it will be in ~/.config/

**Comment by KingBonecrusher** [comment]
Thanks, this solved my problem! Maybe a good idea to add a small font configuration dialog in the future.
