### ISSUE TITLE
[UEFIPatcher] terminal support

### ISSUE THREAD

**Issue by Florin9doi** [LongSoft/UEFITool#186]
Please add back the support for applying patches from terminal: 
[diff_for_master_branch.txt](https://github.com/LongSoft/UEFITool/files/3665335/UEFIPATCH_ARGUMENTS.txt)

**Comment by vit9696** [comment]
Oops, that was missed somehow. Merged, thanks!

**Comment by Florin9doi** [comment]
Thanks. Will you release a new version?
