### ISSUE TITLE
UEFITool causes the system to OOM on invalid data

### ISSUE THREAD

**Issue by hughsie** [LongSoft/UEFITool#191]
I mistakenly tried to load a system firmware with a PFS header. After a few seconds my system froze, and on a tty console UEFITool was using 32GB of ram, increasing by about 2GB per second. A file you can use to reproduce this is https://people.freedesktop.org/~hughsient/temp/firmware-OOM-UEFIExtract.bin -- thanks!

**Comment by vit9696** [comment]
Thanks for the report, fixed in master:

```
[new_engine bf3adbe] Fix infinite loop due to 0-sized volume files
 1 file changed, 5 insertions(+)
```

**Comment by hughsie** [comment]
Works great, thanks!
