### ISSUE TITLE
Regions past EC aren't detected by old engine, which breaks modified images

### ISSUE THREAD

**Issue by NikolajSchlej** [LongSoft/UEFITool#192]
Old engine's descriptor parsing code was written in 2014 and hasn't been improved much since then, so it can't see modern regions that aren't Descriptor/ME/GbE/BIOS/PDR/EC, and this breaks 
[C621D8A210.zip](https://github.com/LongSoft/UEFITool/files/4112222/C621D8A210.zip)
images like the attached one.

**Comment by CrazyHulk** [comment]
Does lastest version have solve this?
I have find patch in patches.txt for C620.
`# PpmInitialize | 0xE2 & 0x1AA unlock for C620 Chipsets
3FFCAE95-23CF-4967-94F5-16352F68E43B 10 P:480BC2BA00200000:480BC2BA00000000 
3FFCAE95-23CF-4967-94F5-16352F68E43B 10 P:480BC2BA00800000:480BC2BA00000000`
Does it works for C621?

**Comment by NikolajSchlej** [comment]
Even if t works, the resulting file will be broken due to regions past EC being missing after patching (the bug is about that).

**Comment by CrazyHulk** [comment]
> Even if t works, the resulting file will be broken due to regions past EC being missing after patching (the bug is about that).

Sorry to bother you, is this feature still under development?

**Comment by NikolajSchlej** [comment]
It is, albeit really slow due to me being on vacation. Will return to it when the time is right.

**Comment by NikolajSchlej** [comment]
I'm mass-closing all issues that are specific to the old engine, because no further work is planned to be done on it, and all the bugs that are present there are to remain there forever. The original engine had a good run, but it needs to go in peace.

**Comment by crazyhulk** [comment]
> I'm mass-closing all issues that are specific to the old engine, because no further work is planned to be done on it, and all the bugs that are present there are to remain there forever. The original engine had a good run, but it needs to go in peace.

Does new engine can unlock 0xE2 & 0x1AA?
