### ISSUE TITLE
UF/UE bug

### ISSUE THREAD

**Issue by LSSoniX** [LongSoft/UEFITool#208]
Всем доброго здравия!

Посмотрите пожалуйста этот файл
https://ufile.io/shbe696p
UEFIFind и Extract крэшатся на нем даже на простых запроосах типа uefiextract <файл биоса>
UEFITool'ы открывают без проблем
UEFIReplace пока не проверял.
Спасибо.

**Comment by vit9696** [comment]
Привет!

У меня всё ок на ветке из мастера, я отправил на сборку последние версии вот сюда: https://github.com/LongSoft/UEFITool/releases/tag/t20200508. Возможно проблема была исправлена.

Вит

**Comment by LSSoniX** [comment]
Да, эти сборки исправились. Спасибо! :))

А была вот такая ерунда
![zzz](https://user-images.githubusercontent.com/20858707/81428361-d684b580-9164-11ea-8d43-2f388fed7fca.JPG)

**Comment by vit9696** [comment]
Отлично, тогда через какое-то время выложу новую версию.
