### ISSUE TITLE
[patch] FPT parser: make ME8 bizzare name visible

### ISSUE THREAD

**Issue by nms42** [LongSoft/UEFITool#214]
[me8-name.diff.txt](https://github.com/LongSoft/UEFITool/files/4992837/me8-name.diff.txt)

**Comment by nms42** [comment]
The patch for new_engine.

**Comment by NikolajSchlej** [comment]
Need more information on this. What is that bizzare name, where it comes from, is there a BIOS image with that name, etc.
The patch is trivial, but the story behind it is not.

**Comment by nms42** [comment]
The name is \0xE0\x15\x00\x20. Unprintable by itself. That name is the bug in ME8 tools, probably. Attached the sample. The BIOS is for Toshiba Satellite L830 (almost legacy). I have seen that name in some other BIOSes too.

[bu8-bios-7.orig.fd.zip](https://github.com/LongSoft/UEFITool/files/4996187/bu8-bios-7.orig.fd.zip)

**Comment by NikolajSchlej** [comment]
Need to improve it into a generic "display names as 8 hex digits if 4 char name has non-numeric-non-alphabet symbols". This will resolve this issue and all similar ones.

**Comment by nms42** [comment]
And when there is a mixture of visible/invisible bytes? All to hex?

**Comment by nms42** [comment]
Separate function in common/utility.cpp?

**Comment by vit9696** [comment]
Yes, mixing ASCII and HEX will not do good for us. A function in utility.cpp sounds good to me.

**Comment by nms42** [comment]
OK,
here is next attempt

[vh.diff.txt](https://github.com/LongSoft/UEFITool/files/5012222/vh.diff.txt)

**Comment by NikolajSchlej** [comment]
Fixed in 115d338
