### ISSUE TITLE
[NE] ME FPT parser: false "invalid checksum" message when ROM Bypass present and not Empty(0x00)

### ISSUE THREAD

**Issue by nms42** [LongSoft/UEFITool#215]
I have no patch yet.

**Comment by nms42** [comment]
In that case FPT header length == 0x30.

**Comment by NikolajSchlej** [comment]
Need a BIOS image that reproduces the issue in the current code.

**Comment by nms42** [comment]
Attached BIOS for Toshiba Satellite L830 with such fpt header.

[bu8-bios-7.orig.fd.zip](https://github.com/LongSoft/UEFITool/files/4996219/bu8-bios-7.orig.fd.zip)

**Comment by asgmeonerandom** [comment]
@nms42 sorry not related but how did you get the bios image?

**Comment by nms42** [comment]
Just unpacked 6.60 version for Toshiba Satellite L830 downloaded from dynabook (former toshiba) site with 7zip. The *.fd file.

**Comment by NikolajSchlej** [comment]
Fixed in 3945c9b.
