### ISSUE TITLE
Add support for FPT Header version 0x21 with crc32 checksum (Intel TigerLake+)

### ISSUE THREAD

**Issue by nms42** [LongSoft/UEFITool#216]
No patch yet

**Comment by nms42** [comment]
Author of MEAnalyzer wrote to me: version 0x21 will be in firmware for TigerLake and following.

**Comment by NikolajSchlej** [comment]
Need a BIOS image sample here before we go change the code.

**Comment by nms42** [comment]
There are no BIOSes with 0x21 headers yet.

**Comment by NikolajSchlej** [comment]
Let's wait for such a sample then before changing the code.

**Comment by ValZapod** [comment]
There are samples in Intel leak. Crazy amount of them.

**Comment by NikolajSchlej** [comment]
Found an image with FPT 0x21 header, uploading for future reference.
[ROG-MAXIMUS-Z690-HERO-ASUS-1720.CAP.zip](https://github.com/LongSoft/UEFITool/files/9421773/ROG-MAXIMUS-Z690-HERO-ASUS-1720.CAP.zip)

**Comment by NikolajSchlej** [comment]
An image with FPT 0x20 header to test the other code branch.
[MAXIMUS-IV-GENE-Z-GEN3-ASUS-3603.ROM.zip](https://github.com/LongSoft/UEFITool/files/9422214/MAXIMUS-IV-GENE-Z-GEN3-ASUS-3603.ROM.zip)

**Comment by NikolajSchlej** [comment]
Resolved in A60, will be released soon.
