### ISSUE TITLE
Ignore Intel Flash Descriptor dummies at AMD BIOS images

### ISSUE THREAD

**Issue by platomav** [LongSoft/UEFITool#234]
HP seems to be using a dummy Intel Flash Descriptor structure at some AMD BIOS images, probably to satisfy their internal tools or something.

Obviously that causes false positives and errors/crashes at firmware parsers like UT so it should be ignored by adjusting the FD detection.

![Eq-95m3XEAA7YQY](https://user-images.githubusercontent.com/11527726/103689112-8a13a300-4f9b-11eb-9d36-d309c66f6250.png)

Checking that the 1st byte after the Signature (Flash Component Base Address, FCBA) is within the future-proof range of 01-10h should be enough. Future proof because ICH8-ICH10 = 1, IBX = 2 and CPT+ = 3.

[087FA_F02.zip](https://github.com/LongSoft/UEFITool/files/5772108/087FA_F02.zip)

**Comment by NikolajSchlej** [comment]
We already have a check for a valid master base, the issue here is caused by incorrect fallback to raw area parsing in case Capsule or IntelDescriptor parsing failed. 
Fixed in https://github.com/LongSoft/UEFITool/commit/3a2072cfcbb50bd656372ca0cc2daf3d6dc39cbf

**Comment by platomav** [comment]
Yes, it does seem to be working with the latest commits now:

![Screenshot 2023-02-18 143601](https://user-images.githubusercontent.com/11527726/219866159-667027d0-8aca-49a0-b105-fe2948d5dbee.jpg)

**Comment by NikolajSchlej** [comment]
Had to revert a fixing commit due to breakages introduces in the fuzzing-errors-fixing ones, will reapply.

**Comment by NikolajSchlej** [comment]
Fixed again in https://github.com/LongSoft/UEFITool/commit/2d1ebcc11b9af03fa7ba779ebef80517cb1a3f65

**Comment by platomav** [comment]
Indeed, can confirm that https://github.com/LongSoft/UEFITool/commit/2d1ebcc11b9af03fa7ba779ebef80517cb1a3f65 solves it.
