### ISSUE TITLE
Bios corruption after "17088572-377F-44EF-8F4E-B09FFF46A070" microcode file adjusted with ver 0.28

### ISSUE THREAD

**Issue by davidm71** [LongSoft/UEFITool#235]
Hi,

Recent mod caused post failure after modifying microcode file "17088572-377F-44EF-8F4E-B09FFF46A070" and replacing "as is"  using UEFITool. This resulted in  extra hex values that normally do not exist in the end of the FIT table or at the beginning of the Microcode file when looking at the bios file in a hex editor. Adjustments made to FIT table to match start address of each microcode as is the process however even though the final bios file looked good in Uefitool NE58 or Ubitool and flashed without issue system failed to post on an Asrock X299_OCF bios file.  Had success using MMTool 5.02.0024 to manually add and remove microcode files.  The details can be found here:

https://www.win-raid.com/t3132f47-GUIDE-AMI-INTEL-CPU-Microcode-Update-Guide-24.html#msg136171

**Comment by NikolajSchlej** [comment]
I'm mass-closing all issues that are specific to the old engine, because no further work is planned to be done on it, and all the bugs that are present there are to remain there forever. The original engine had a good run, but it needs to go in peace.
