### ISSUE TITLE
Need splits PAD for multibody  pad

### ISSUE THREAD

**Issue by slavonnet** [LongSoft/UEFITool#252]
Need convert  pad to list if pads (regions) ifs insude more than one type of dats

Now pad can
- Be zerro
- Be FF
 - Containts CPU Firmware
 - Contaionts VTB (Vga Bios)
 - Containts SSL Keys

If pad have more than 1 region need to add sublist with region and type information

I think is bloker issue.  You look to pad and think that its one object but inside you have 3+

**Comment by NikolajSchlej** [comment]
None of the cases you mentioned are compliant to UEFI specification, that clearly states that PAD files must be filled by volume's erase polarity bit, and any data in those PAD files should make them into RAW files instead. The fact that we need to build non-empty PAD files properly in new_engine is known, and anticipated for, and old engine is not supported at this point, so this is certainly not a blocker of any kind.
