### ISSUE TITLE
UEFITool "Insert after" doesn't work in last version.

### ISSUE THREAD

**Issue by Tamago4a** [LongSoft/UEFITool#253]
[BIOS](https://sampawno.ru/download/file.php?id=1757&filename=X9DRD78_823.zip)

Version UEFITool v0. 28
![Модификация BIOS MT25QL128AB для поддержки NVMe m 2 ssd дисков](https://user-images.githubusercontent.com/47304666/144752763-6014c790-c0a6-4017-acef-f9a371e3401f.png)

Version UEFITool_NE_A59_win32
![Безымянный](https://user-images.githubusercontent.com/47304666/144752810-0a9afea0-850b-4416-af82-b01d591e0001.png)

**Comment by vit9696** [comment]
https://github.com/LongSoft/UEFITool/issues/67
