### ISSUE TITLE
How to build project for win32

### ISSUE THREAD

**Issue by greg0r0** [LongSoft/UEFITool#264]
Hi

I want to do smth changes for me in this project, but  absolutely don't understand how it must be builded on Ubuntu 20.04 or Win11 or in QT Creator. Unified script (unixbuild.sh) seems like very complicated.

I tryed to change pacman to apt and correct repos, force change $UPLATFORM variable to win32, but script just give some errors like "cant find UEFITool.exe" . About QT creator i can't say anything, i dont see cmake files for UEFITool. If i try to build "by hands" i get a bunch of errors about QT libs.

Can you help and give more advices about build process? Info in README dont see very useful.

**Comment by NikolajSchlej** [comment]
The unixbuild.sh script is mostly for using in CI/CD pipeline, so it attempts to download and install a static release-only built of Qt 5.6.3, which is not something you want for ongoing development.

What exactly is the issue with this part of the README in new_engine branch?
- To build a binary that uses Qt library (UEFITool) you need a C++ compiler and an instance of [Qt5](https://www.qt.io/) library. Install both of them, get the sources, generate makefiles using qmake ('qmake UEFITool.pro') and use your system's make command on that generated files (i.e. 'nmake release', 'make release' and so on).

The project file for UEFITool is UEFITool.pro, and QtCreator can open and build it natively.

**Comment by NikolajSchlej** [comment]
Setup an Ubuntu VM specifically for building UEFITool, here are the required terminal commands:
- to install C++ compiler and related tools: 'sudo apt install build-essential'
- to install Qt5 development tools: 'sudo apt install qt5base-dev qt5-qmake'
- to obtain UEFITool sources from GitHub: 'git clone https://github.com/LongSoft/UEFITool ~/UEFITool'
- to create a build folder (so build artefacts aren't get scattered everywhere): 'cd ~/UEFITool; mkdir build; cd build'
- to create a Makefile from Qt5 project file: 'qmake ../uefitool.pro'
- to build an executable image: 'make'

**Comment by greg0r0** [comment]
BTW there is only errors about usprintf format. Maybe here can be some easy fix? I deleted macros `__PRI_64_LENGTH_MODIFIER__` at `UEFITool\common\uinttypes.h` types and project successfully builded, but i feel it was bad move :D

![изображение](https://user-images.githubusercontent.com/36220096/177541514-5e7be9b1-605b-4b08-838e-4e44ff971957.png)

P.s. using new_engine branch

**Comment by NikolajSchlej** [comment]
What C++ compiler do you have installed?
