### ISSUE TITLE
How UEFIReplace works?

### ISSUE THREAD

**Issue by DDarknessOne** [LongSoft/UEFITool#265]
I would like to replace one Compressed Section, but i always get "Function called with invalid parameter".
I tried to use with this: UEFIReplace.exe F:\msibiosoriginal.bin B7D19491-E55A-470D-8508-85A5DFA41974 01h F:\white.bin
This i what i trying to replace: https://i.ibb.co/3WRZcqj/image.png
But i want it with command line arguments.

**Comment by NikolajSchlej** [comment]
Put -o before F:\white.bin.
