### ISSUE TITLE
Fails to compile with QT6

### ISSUE THREAD

**Issue by hughsie** [LongSoft/UEFITool#278]
QT5 works fine, QT6 fails with:

	../common/nvramparser.cpp: In member function ‘USTATUS NvramParser::parseNvarStore(const QModelIndex&)’:
	../common/nvramparser.cpp:95:51: error: expected ‘)’ before ‘__PRI_64_LENGTH_MODIFIER__’
	   95 |             UString info = usprintf("Full size: %" PRIXQ "h (%" PRIuQ ")", padding.size(), padding.size());

**Comment by NikolajSchlej** [comment]
Compiler type and version, exact Linux variant, anything to ease reproduction of it?

**Comment by NikolajSchlej** [comment]
Reproduced, fixing.

**Comment by NikolajSchlej** [comment]
Fixed.
