### ISSUE TITLE
Open multiple bios files

### ISSUE THREAD

**Issue by gdbinit** [LongSoft/UEFITool#28]
It's not possible to open multiple bios files at the same time, at least in the OS X version.
It would be great to have an option to open a new window for working on another bios file.
Usually this is very useful for comparing changes and so on.

fG!

**Comment by NikolajSchlej** [comment]
I'm not a fan of MDI or tabbed interface, but I can add "Open file in new window..." into File menu with ease. Will be done together with new engine release.

**Comment by gdbinit** [comment]
A new window would be a great feature.

**Comment by NikolajSchlej** [comment]
Will be added in one of upcoming versions then.

**Comment by NikolajSchlej** [comment]
Solved in 0.20.7 for master branch by adding "Open in new window..." action.
