### ISSUE TITLE
Meson-produced binaries have all optional features disabled

### ISSUE THREAD

**Issue by NikolajSchlej** [LongSoft/UEFITool#289]
Did some testing using GH actions while preparing the Kaitai-BG PR, and found out that both UEFIExtract and UEFIFind that are built by Meson are getting built with all optional features disabled, i.e. this part:
```
  c_args: [
    '-DU_ENABLE_NVRAM_PARSING_SUPPORT',
    '-DU_ENABLE_ME_PARSING_SUPPORT',
    '-DU_ENABLE_FIT_PARSING_SUPPORT',
    '-DU_ENABLE_GUID_DATABASE_SUPPORT',
  ]
```
has no effect.

@hughsie, do you know a way to fix it?

**Comment by hughsie** [comment]
Hmm, I see the same too -- weird. Investigating.

**Comment by hughsie** [comment]
Ha, it needs to be cpp_args when using the C++ compiler. PR incoming
