### ISSUE TITLE
Most recent commit has broken ROM parsing

### ISSUE THREAD

**Issue by mikebeaton** [LongSoft/UEFITool#327]
The [most recent commit](https://github.com/LongSoft/UEFITool/commit/7337f15ec9498d6e526f042dcb46a42220a47cf4) seems to have broken ROM parsing - this is a standard 144.0.0.0.0 Mac Pro ROM.

Before recent commit:

<img width="909" alt="Screenshot 2023-01-02 at 11 18 20" src="https://user-images.githubusercontent.com/11946605/210224524-e8e8a372-6daa-403e-a265-7c236c644fa3.png">

After:

<img width="917" alt="Screenshot 2023-01-02 at 11 18 51" src="https://user-images.githubusercontent.com/11946605/210350717-4a58dc05-769b-48ff-81af-a8ee09bccdf3.png">

**Comment by NikolajSchlej** [comment]
Should be fixed in 19ab6076c48b2fc43856e784148fc571142f7891

**Comment by mikebeaton** [comment]
Yes, fixed and appears to be displaying/extracting sections correctly again - tyvm
