### ISSUE TITLE
Identified some additional errors mistakenly introduced into guids.csv

### ISSUE THREAD

**Issue by mikebeaton** [LongSoft/UEFITool#329]
I identified some further [g|G][A-Z] issues introduced in https://github.com/LongSoft/UEFITool/commit/0fb88ab76035df49fd7967f43e207b77c68ad363 , e.g. `SlingShot` -> `SlinShot`, `OemBadgingSupportDxe` -> `OemBadginSupportDxe`, also `BFGSmm` -> `BFSmm`.

Some have been fixed since, by 44c5b4bc49f713b42675f3f50e68fbae8f196e8b and https://github.com/LongSoft/UEFITool/commit/1b143c89e6e8fd00af2dda2ab2455b68a3b2bfda .

Having identified the (a?) pattern for these, I have put together another PR fixing the (some?) remaining ones.

**Comment by NikolajSchlej** [comment]
Looks like this is now fixed, closing as so.

**Comment by mikebeaton** [comment]
Ah, I didn't check, I was expecting GitHub to automatically close it if the related PR was merged, since I mentioned the issue number in the PR comment. (Almost 100% certain I've seen that happen before, with the issue number where I put it, so not sure if GitHub have changed their settings, or if it's a per-repo setting.) Thx.
