### ISSUE TITLE
Does new engine support Cascade.

### ISSUE THREAD

**Issue by crazyhulk** [LongSoft/UEFITool#332]
The old engine not work for [epc621d8a](https://download.asrock.com/BIOS/Server/EPC621D8A(2.10)ROM.zip) when I try to unlock 0xE2.
And it breaks modified images.

Does the new engine had fix this?

[some discussions](https://github.com/LongSoft/UEFITool/issues/91)

**Comment by NikolajSchlej** [comment]
Parsing is perfectly fine in new_engine, but builder is still not ready, so there's currently no way to perform modification with it.

Meanwhile, you can do the following:
- Open you file in UEFITool NE and extract BIOS region from it
- Use UEFIPatch to patch that BIOS region file
- Open the original file in a hex editor and replace the whole BIOS region in the original file with the result of UEFIPatch modification. 

In the file you've linked, BIOS region starts at exactly the middle (16Mb mark, offset 0x1000000).

**Comment by crazyhulk** [comment]
Yes, new_engine parsing perfectly fine and the patch method works, but the 0xE2 will rewrite to 1 when wake from sleep.

In short, the CFG Lock will be enable after wake from sleep.

How did I found this?
1.  Open you file in UEFITool NE and extract BIOS region from it
2.  Use UEFIPatch to patch the BIOS region file
3.  Cut bios file  to keep bios start to offset 0x1000000 by dd command (as file A)
4.  Concat the file from step 3 and patched BIOS region file. (cat A B > C)
5.  Flash the BIOS
6.  Use RW Everything to check 0xE2, which be disabled as expected.
7.  Sleep and wake
8.  Use RW Everything to recheck 0xE2, which be enabled.

Is there something wrong?

@NikolajSchlej

**Comment by NikolajSchlej** [comment]
If it gets re-enabled, there's a second piece of code (most likely in PEI or in S3 bootscript) that does that, and it also needs to be patched away. I'm currently traveling and don't have access to the tools required to investigate where that code is, so please remind me in a week about that.

**Comment by crazyhulk** [comment]
Have a pleasant journey.

Have you finished your trip? 

Please take a look at  0xE2 re-enable  when you have some time.

@NikolajSchlej

**Comment by NikolajSchlej** [comment]
Done now, will check on the weekend.

**Comment by NikolajSchlej** [comment]
Checked that out, looks like the lock is getting set by CpuPei module during S3 wake. It is covered by BootGuard, so patching it out might make the board unbootable. Needs some testing, and likely can be patched a different way that doesn't trigger it. If you are willing to test (and have a SPI flasher to recover from broken BIOS), ping me here, I'll prepare a modded file.

**Comment by crazyhulk** [comment]
I am willing to test, but I need another windows machine use SPI flasher to force flash bios. The test may cost more time.

**Comment by crazyhulk** [comment]
> Checked that out, looks like the lock is getting set by CpuPei module during S3 wake. It is covered by BootGuard, so patching it out might make the board unbootable. Needs some testing, and likely can be patched a different way that doesn't trigger it. If you are willing to test (and have a SPI flasher to recover from broken BIOS), ping me here, I'll prepare a modded file.

Ping @NikolajSchlej .

Sorry, this matter has been put on hold for a long time. I can make  testing at any time now.
Looking forward to your mod file!

**Comment by NikolajSchlej** [comment]
Put this on my todo list, will check on one of the next weekends.

**Comment by crazyhulk** [comment]
Thx, waiting for your good news.​

**Comment by crazyhulk** [comment]
Happy new year! 🎉🎉🎉 @NikolajSchlej 

Has there been any progress?

**Comment by NikolajSchlej** [comment]
None, completely forgot about this, life got busier lately. Can't promise anything other than keeping this in mind.

**Comment by crazyhulk** [comment]
> None, completely forgot about this, life got busier lately. Can't promise anything other than keeping this in mind.

The busier life makes it easy to forget this.

Life first! Do not need promise anything!
