### ISSUE TITLE
Question: how can i modify my Acer uefi that is packed in a .4m file?

### ISSUE THREAD

**Issue by Delfo19** [LongSoft/UEFITool#333]
Hi, i have my Acer Veriton X 2630G and i want to change his boot logo but i can't find a way to unpack his uefi file.
Does someone know how to do it?
![Immagine 2023-01-17 170244](https://user-images.githubusercontent.com/103816175/212949057-35984f77-dfcb-471e-b36a-bb956c68df45.png)

**Comment by NikolajSchlej** [comment]
![1](https://user-images.githubusercontent.com/1845688/215360143-4a8f91bd-3cab-450a-a91c-698dd43a5473.png)
This is a BIOS region image from a typical AMI AptioV, you can modify it using PhoenixTool or UEFITool 0.28
