### ISSUE TITLE
Hex/Text search doesn't find in LZMA compressed section while GUID search works

### ISSUE THREAD

**Issue by xCuri0** [LongSoft/UEFITool#335]
BIOS is from ASUS Z170-E version 3801

Searching ```PciBus``` in text search or ```CF8034BE``` (PciHostBridge allocation protocol) in hex search finds nothing. However searching ```CF8034BE``` in GUID search works and shows this.

![image](https://user-images.githubusercontent.com/29529557/215007165-ef40da9e-68a6-4191-bde8-26719c7a6dc8.png)

There's a visible PciBus string so shouldn't atleast text search find it ?

**Comment by NikolajSchlej** [comment]
You have the answer on your screenshot: "GUID pattern CF8034BE ... found as BE3480CF...".
The GUID of 00112233-4455-6677-8899-AABBCCDD is stored as "33221100554477668899AABBCCDD" because x86 is little-endian. It's not a bug in UEFITool, it's how UEFI GUIDs are stored on x86.

**Comment by xCuri0** [comment]
@NikolajSchlej what about text search. It also finds nothing when I look for ```PciBus``` which is clearly visible. Usually it finds DXE modules by name but it doesn't find this one

**Comment by NikolajSchlej** [comment]
Make sure to select Unicode for that UI sections text.

**Comment by NikolajSchlej** [comment]
<img width="1036" alt="Screenshot 2023-01-26 at 23 08 53" src="https://user-images.githubusercontent.com/1845688/215028861-44d8898b-3556-40d4-8aed-44de349b8461.png">

**Comment by NikolajSchlej** [comment]
The name in your BIOS is not coming from an UI section, however, but from GUID database, that's why you can't find that text using "Search...".

**Comment by NikolajSchlej** [comment]
<img width="1038" alt="Screenshot 2023-01-26 at 23 12 23" src="https://user-images.githubusercontent.com/1845688/215029430-d0ee0ea5-6a9a-400e-8d8a-8fceb5c99bdf.png">

**Comment by NikolajSchlej** [comment]
You can unload the GUID database by using "File->Unload GUID Database", then (re)open your file and see that the names are now shown as GUIDs, and there's no "PciBus" unicode text to be found anywhere.

We do have some ideas on improving search and implementing GUID-database-assisted search, but it's a low priority feature currently.

**Comment by xCuri0** [comment]
@NikolajSchlej thanks for explaining why the text search won't work
