### ISSUE TITLE
Add UEFITool version number to About...

### ISSUE THREAD

**Issue by nms42** [LongSoft/UEFITool#337]
Subject says all

**Comment by NikolajSchlej** [comment]
<img width="1039" alt="Screenshot 2023-02-03 at 09 07 05" src="https://user-images.githubusercontent.com/1845688/216664027-3a9d7962-48bf-48cd-9235-2d0a0440898c.png">
Is window header visible enough?

**Comment by NikolajSchlej** [comment]
Will add it to About, because the change is trivial and makes sense.

**Comment by NikolajSchlej** [comment]
![1](https://user-images.githubusercontent.com/1845688/216751903-11754cc2-f9bf-4c0f-8397-bc7e1f11f46e.png)
Done in https://github.com/LongSoft/UEFITool/commit/f02f828571d64b14410faea6b9144faeccedcd7a
