### ISSUE TITLE
Unicode text search is broken in v64

### ISSUE THREAD

**Issue by mikebeaton** [LongSoft/UEFITool#347]
If I search for a unicode string which I know is present (e.g. 'bluetooth', 'apple') in a given ROM, v63 finds it, v64 returns no results.

**Comment by NikolajSchlej** [comment]
Duplicate of #341, fixed, the fix will be a part of A65.

**Comment by mikebeaton** [comment]
Ah sorry about the two duplicates, I looked in open issues - should have looked carefully at closed of course too - thanks for your ongoing work!
