### ISSUE TITLE
UEFITool is no longer packaged as an App

### ISSUE THREAD

**Issue by mikebeaton** [LongSoft/UEFITool#348]
I guess this is intentional? But in the v64 release assets UEFITool_NE_A64_universal_mac.zip does not contain UEFITool as a macOS application, but rather as an executable. An application for this non-command line GUI application is perhaps preferable (e.g. to me - but thought I might as well raise this in case anyone else cares - &/or - unlikely - the change is not on purpose).

**Comment by NikolajSchlej** [comment]
Duplicate of #340, fixed already, the fix will be a part of A65.
