### ISSUE TITLE
Checksums do not fit. Lenovo Z570 bios

### ISSUE THREAD

**Issue by DenSaoPin** [LongSoft/UEFITool#349]
I have a few bios dumps from Lenovo z570 notebook and both have the same warning messages about wrong checksums. 
![image](https://user-images.githubusercontent.com/27866109/222985227-8038faa0-b724-4770-a102-c02551ba9977.png)

So I don't understand the checksum calculation mechanism, but in my opinion it looks a little strange, because there is a sum of 36 numbers, which is subtracted from 0x10000, while the counter overflows several times, is it intended? (calculateChecksums16 function)

Looks like as some missed nuance.

**Comment by NikolajSchlej** [comment]
That BIOS if a Phoenix SCT from 2011, one of the earliest UEFI implementations, so it having somewhat questionable compatibility with UEFI specification is expected.
In the update, there are 4 volumes, with thew two actually having files also having correct checksum, and the other two used for NVRAM having a hardcoded checksum of 0x7A3B. 
Verdict: the tool is right, the image is also fine, please ignore that warning.
