### ISSUE TITLE
how to run uefitool getting error while loading shared libraries: libQt6Widgets.so.6

### ISSUE THREAD

**Issue by kocoman1** [LongSoft/UEFITool#357]
how to run uefitool getting error while loading shared libraries: libQt6Widgets.so.6

**Comment by NikolajSchlej** [comment]
What is your environment? Some kind of Linux, it seems. The build for linux that is in the repo dynamically links Qt6. You can either install it from your package manager, or install UEFITool from FlatHub here: https://flathub.org/apps/details/com.github.LongSoft.UEFITool
