### ISSUE TITLE
Can this tool be used to remove or modify stock firmware modules & drivers?

### ISSUE THREAD

**Issue by ghost** [LongSoft/UEFITool#360]
Can this tool be used to lets say remove [ComuTrace/LoJack](https://www.welivesecurity.com/wp-content/uploads/2018/09/ESET-LoJax.pdf) modules in a firmware or atleast overwrite them similar to *me_cleaner*?

Also can this tool be used remove the blutooth drivers from a stock firmware image? Then reflash it?

**Comment by NikolajSchlej** [comment]
The current version can not perform image modification, only image forensics, the modification part for new_engine is still in early development stages.
However, old engine still works in many cases, the binaries can be downloaded from here: https://github.com/LongSoft/UEFITool/releases/tag/0.28.0
I would also suggest to consider the alternatives mentioned in README.md, especially PhoenixTool and Fiano.

**Comment by ghost** [comment]
@NikolajSchlej 
>I would also suggest to consider the alternatives mentioned in README.md, especially PhoenixTool and Fiano.

[fiano DXE Cleaner](https://github.com/linuxboot/fiano#dxe-cleaner) seems to be what i'm looking for cause I believe **CompuTrace** is a *DXE module*? Also thanks for the info and work.
