### ISSUE TITLE
Can this modify the UEFI of those Chinese motherboards?

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [LongSoft/UEFITool#364]
For example, something like this "B75" board I'm running in my main rig right now. These use an AMI UEFI in particular.
![image](https://github.com/LongSoft/UEFITool/assets/8545874/aff5d26b-09ed-4f98-a343-d5c461936b6c)

**Comment by NikolajSchlej** [comment]
I don't see why not, as this kind of boards are all using AMI AptioV. [UEFITool 0.28.0](https://github.com/LongSoft/UEFITool/releases/tag/0.28.0) is the last version that supports modifications though.
