### ISSUE TITLE
are there plans to for example  extract apple scap firmware bios region and then write it to a ch341a rom dump?

### ISSUE THREAD

**Issue by kocoman2** [LongSoft/UEFITool#369]
are there plans to for example  extract apple scap firmware bios region and then write it to a ch341a rom dump?

i was able to get a mbp8,2 to flash a mbp8,1 with the amd graphics disabled by default (because mbp8,1 don't have amd)
I did that when I used the smc flasher and changed the mbp from 8,2 to 8,1 for some reason.. 

if I just flash the bios region with flashrom on the scap it gives me this error
Error: Image size (8454768 B) doesn't match the expected size (8388608 B)!
8454768 is the scap ..

my bios is already unlocked, because i am using coreboot..  

thx

**Comment by NikolajSchlej** [comment]
No, there are no such plans.
