### ISSUE TITLE
Old haunting issues

### ISSUE THREAD

**Issue by lordkag** [LongSoft/UEFITool#37]
No more candies for you, mister!

- I thought [this issue] (https://github.com/LongSoft/UEFITool/issues/34) is solved in both branches? It looks to be solved in new_engine, based on the UEFIFind_0.10.2 you provided, but not in master branch.
- Maybe I haven't opened Gigabyte images for a long time or this issue is recent, but UEFITool (both branches) is showing an error. It fixes Gigabyte's bug/feature of BIOS region base, but it then uses the initial wrong size to check for image consistency. Take [any image from Station-Drivers] (http://www.station-drivers.com/index.php?option=com_content&view=category&id=140&Itemid=169&lang=fr) as an example.

**Comment by NikolajSchlej** [comment]
Problems solved, new versions released, issue closed, enough candies left!
