### ISSUE TITLE
Off-by-one error preventing parsing of Boot5 partition in IFWI 1.6 and 1.7 regions

### ISSUE THREAD

**Issue by NikolajSchlej** [LongSoft/UEFITool#376]
Finally found an image in the wild that has Boot5 region populated (and using legacy $FPT format).

```
    // Add boot partitions
-   for (UINT8 i = 0 ; i < 4; i++) {
+   for (UINT8 i = 0 ; i < 5; i++) {
        if (ifwiHeader->BootPartition[i].Offset != 0 && ifwiHeader->BootPartition[i].Offset != 0xFFFFFFFF) {
            IFWI_PARTITION_INFO partition = {};
            partition.type = Types::IfwiPartition;
```

**Comment by XutaxKamay** [comment]
> Finally found an image in the wild that has Boot5 region populated (and using legacy $FPT format).
> 
> ```
>     // Add boot partitions
> -   for (UINT8 i = 0 ; i < 4; i++) {
> +   for (UINT8 i = 0 ; i < 5; i++) {
>         if (ifwiHeader->BootPartition[i].Offset != 0 && ifwiHeader->BootPartition[i].Offset != 0xFFFFFFFF) {
>             IFWI_PARTITION_INFO partition = {};
>             partition.type = Types::IfwiPartition;
> ```

Can you share the image in question?

**Comment by NikolajSchlej** [comment]
[MAIN.zip](https://github.com/LongSoft/UEFITool/files/12564065/MAIN.zip)
![1](https://github.com/LongSoft/UEFITool/assets/1845688/f84a5eac-9b51-43cc-afb7-b4c3feac35b3)
