### ISSUE TITLE
Can not extract VBIOS and GOP

### ISSUE THREAD

**Issue by peter-held** [LongSoft/UEFITool#385]
Hi,

I tried to extract VBIOS and GOP from this Intel NUC BIOS update and I couldn't find them.

Can you help me with it, please ?

You can download the BIOS file from here:
https://www.intel.com/content/www/us/en/download/773996/bios-update-anrpl357.html

Thanks.

**Comment by NikolajSchlej** [comment]
The file is not an UEFI image, but an AMI PFAT capsule that needs to be extracted first using @platomav's excellent [BIOSUtilities](https://github.com/platomav/BIOSUtilities) toolset, namely [AMI_PFAT_Extract.py](https://github.com/platomav/BIOSUtilities/blob/main/AMI_PFAT_Extract.py) script.

Once extracted, the resulting *_ALL.bin file can be opened in UEFITool as usual, and will have both VBIOS and GOP visible in the tree.

[00 -- AN0027.CAP_ALL.bin.zip](https://github.com/LongSoft/UEFITool/files/13556369/00.--.AN0027.CAP_ALL.bin.zip)

**Comment by peter-held** [comment]
I still can not find them.

After opening the .bin file in UEFITool,  I'm expecting to see something like here:

https://github.com/Kethen/edk2/blob/edk2-intel-gop/extract_vbt_gop.md

Which names should I look for ?

Thanks.

**Comment by NikolajSchlej** [comment]
<img width="1227" alt="VBT" src="https://github.com/LongSoft/UEFITool/assets/1845688/bc8751dc-5eb9-4921-854a-89f46722d729">
<img width="1232" alt="VBIOS" src="https://github.com/LongSoft/UEFITool/assets/1845688/003ab5d2-6a97-450a-99b6-d4c93e60049b">
Haven't found the GOP driver, but it's most likely implemented as a combination of an Intel Graphics PEI driver and OemGop driver that just republishes the protocol.

**Comment by peter-held** [comment]
Thanks for the hints.

I could find two versions of VBIOS inside:
- for ALDERLAKE-P from 27.03.2015
- for ICELAKE from 15.11.2018

Do you know why there are two of them (my processor is I5-1340P, so ALDERLAKE-P seems better) ?

![1](https://github.com/LongSoft/UEFITool/assets/23695480/62455ca7-9d2d-41d8-89e0-211377d9acf2)
![2](https://github.com/LongSoft/UEFITool/assets/23695480/96af8178-5817-498a-9760-811712115322)

Regarding the GOP driver, is it possible to build it from what's inside the BIOS file ?

I need both of them in order to build the Ovmf file for GPU passthrough, like here:
https://github.com/Kethen/edk2

**Comment by NikolajSchlej** [comment]
Take whatever is closer to your real configuration.

No, you can't build a GOP driver for OVMF with what you have there because OVMF lacks a PEI phase. However, it will likely work to grab a GOP driver from BIOS for a similar board that supports same CPU modules, but doesn't use FSP.

**Comment by peter-held** [comment]
Can you tell me how can I do that ?

Thanks.

**Comment by peter-held** [comment]
I found a Dell laptop with the same processor
https://www.dell.com/support/home/en-in/product-support/product/vostro-16-5630-laptop/drivers
extracted the BIOS and GOP Driver.

Can you confirm me, please, that this is what it needs (that doesn't use FSP) ?
[gop.zip](https://github.com/LongSoft/UEFITool/files/13658224/gop.zip)

Thanks.

**Comment by NikolajSchlej** [comment]
Yep, this is a traditional DXE GOP driver.

**Comment by peter-held** [comment]
Thanks.
