### ISSUE TITLE
Bricked after replacing module with UEFITool (ASRock X79 Extreme6/GB)

### ISSUE THREAD

**Issue by segfault-bilibili** [LongSoft/UEFITool#387]
https://winraid.level1techs.com/t/bricked-after-replacing-module-with-uefitool-asrock-x79-extreme6-gb/98853

**Comment by NikolajSchlej** [comment]
Old engine is not supported anymore and no fixes for it will be made. Please try alternative tools like Fiano or PhoenixTool.
