### ISSUE TITLE
UEFITool doesn't recognize lzma compressed section in latest bios

### ISSUE THREAD

**Issue by longnt2007** [LongSoft/UEFITool#388]
Hello,

I have an Asus laptop (X1405ZA) and UEFITool can recognize lzma compression algorithm in old bios (305) and can extract it correctly.
<img width="784" alt="lzma1" src="https://github.com/LongSoft/UEFITool/assets/16752180/4d97bdad-1ef5-49eb-aab7-39a1109d5490">

But in latest bios (313), it no longer detect it as lzma compression algorithm anymore.
<img width="784" alt="lzma2" src="https://github.com/LongSoft/UEFITool/assets/16752180/ab3388d7-ecd6-42c9-98b3-ff67240ba265">

Could you check this issue ? Bios file on Asus support website. Thanks.
https://www.asus.com/in/supportonly/x1405za/helpdesk_bios/

**Comment by NikolajSchlej** [comment]
This is an AMI PFAT image, and needs to be unpacked by a [script](https://github.com/platomav/BIOSUtilities/blob/main/AMI_PFAT_Extract.py) before being opened in UEFITool.
