### ISSUE TITLE
Cant parse image, weird errors. 

### ISSUE THREAD

**Issue by thetechknight** [LongSoft/UEFITool#391]
I have a chromebook style laptop which has some sort of custom vendor hard disk lock on it (Think Lenovo and their wifi card lock) and I tried to open the firmware with this software, but its not really working right. MMTool does it just fine but MMTool is weird with needing to extract everything 1 at a time, whereas I am trying to decompress everything to try to find the "Hard Disk has Changed" string. 

![image](https://github.com/LongSoft/UEFITool/assets/22461464/ff69cbe3-7210-4879-90ca-42abdb89bd50)

Heres the bin: 
[NV116AP_V0D7.zip](https://github.com/LongSoft/UEFITool/files/14392976/NV116AP_V0D7.zip)

Thoughts?

**Comment by NikolajSchlej** [comment]
What exactly makes you believe something is wrong here? The parser messages are info, not errors. Open the regions further and you will see the drivers you can also see with MMTool.
Also, UEFIExtract (a different binary from this repo) is a good commandline tool to extract everything from that image at once,
