### ISSUE TITLE
Selected file is not a proper bios!

### ISSUE THREAD

**Issue by CattoBusiness** [LongSoft/UEFITool#392]
I keep getting the error "Selected file is not a proper bios!" when I try to flash the patched file onto the bios and even when I use old original files (2016 for example) I keep getting the same error... I'm using a Z170-P and I have a Intel Arc A380 and I want to flash it so I can get resizable bar support.

**Comment by MrAnonymous7122** [comment]
I also have the same problem with an Asus H110M-R. I was following the instructions to enable [ReBAR](https://github.com/xCuri0/ReBarUEFI/wiki/Adding-FFS-module) but the current BIOS would refuse to flash it. Also note that these somewhat newer Asus motherboards take .cap files for BIOS (The Z170-P is also Asus and requires a .cap file for BIOS). Mine wouldn't let me flash a .rom and I got the error above when saving the BIOS as bios.cap as its name. Windows showed it as a .cap file but I think that's just purely file extensions. Is it possible for UEFITool to save modified BIOS files as .cap or is it just saving a .rom file that the system believes it to be a .cap? The latter would make sense for this issue however is it possible to add this to UEFITool? I'm no expert but someone on superuser told me that there's a way to add .cap header to .rom file to make it a .cap file? This may be completely wrong and apologies if it is something that would be time consuming to add.
