### ISSUE TITLE
Please help GUID defined section with unknown processing method errors

### ISSUE THREAD

**Issue by zgrcn41** [LongSoft/UEFITool#394]
parseImageFile: Aptio capsule signature may become invalid after image modifications
parseBios: one of volumes inside overlaps the end of data
parseBios: one of volumes inside overlaps the end of data
parseSection: GUID defined section with unknown processing method
parseSection: GUID defined section can not be processed
parseBios: one of volumes inside overlaps the end of data
parseBios: one of volumes inside overlaps the end of data
parseSection: GUID defined section with unknown processing method
parseSection: GUID defined section can not be processed

Errors

parseBios: one of volumes inside overlaps the end of data
parseBios: one of volumes inside overlaps the end of data
parseSection: GUID defined section with unknown processing method
parseSection: GUID defined section can not be processed
No patches can be applied to input file

**Comment by zgrcn41** [comment]
Nothing my mb ı think ım so tired finding double searchs double bios  for uefi tool shit

**Comment by NikolajSchlej** [comment]
Link to the bios?

**Comment by zgrcn41** [comment]
https://dlcdnets.asus.com/pub/ASUS/mb/BIOS/PRIME-B450M-A-II-ASUS-4410.zip?model=PRIME%20B450M-A%20II

**Comment by zgrcn41** [comment]
> Link to the bios?

https://dlcdnets.asus.com/pub/ASUS/mb/BIOS/PRIME-B450M-A-II-ASUS-4410.zip?model=PRIME%20B450M-A%20II

**Comment by NikolajSchlej** [comment]
You can safely ignore all those messages, as they are informational, not errors. However, you can not ignore the very last one: "No patches can be applied to input file".
Your BIOS doesn't have the bytes that your patches.txt tries to patch, so there's nothing to patch in your BIOS.

**Comment by zgrcn41** [comment]
> Hata değil, bilgi amaçlı oldukları için tüm bu mesajları güvenle göz ardı edebilirsiniz. Ancak sonuncuyu göz ardı edemezsiniz: "Giriş dosyasına hiçbir yama uygulanamaz". BIOS'unuzda patch.txt dosyanızın yamamaya çalıştığı baytlar bulunmadığından BIOS'unuzda yamalanacak hiçbir şey yoktur.

So what does this mean? Can't it be changed? Can't the BIOS be changed?

**Comment by NikolajSchlej** [comment]
It means the patches you are trying to apply can not be applied. Need different set of patches developed for your BIOS. It's not changed because there is nothing to change in it.

**Comment by zgrcn41** [comment]
Can you give me sets for my bios please 

> It means the patches you are trying to apply can not be applied. Need different set of patches developed for your BIOS. It's not changed because there is nothing to change in it.

**Comment by zgrcn41** [comment]
İ want to resize bar mod for my bios for rtx 16 20 series someone help

**Comment by NikolajSchlej** [comment]
You need to ask this question in ReBAR repo issues, UEFITool is not relevant here.
