### ISSUE TITLE
commandline options

### ISSUE THREAD

**Issue by vikasnkumar** [LongSoft/UEFITool#4]
Hi,

Is there a way to run this without the UI and just via command-line ? I want to embed this tool into a custom Linux distro that will have no X-server and no mouse inputs either.
It would be great if you could do this or at least inform me on how to go about it and I can give you a pull request for it.

Or can I just use the FFSEngine class to do all the work without the UEFITool class ?

--Thanks.

**Comment by Zibri** [comment]
uefiextract creates too long paths in windows.. which is of if extracting a full image but not ok if you need to extract a single GUID

**Comment by NikolajSchlej** [comment]
Try UEFIDump, it extracts everything into a single subfolder
