### ISSUE TITLE
Couple of GUIDs that are not being identified

### ISSUE THREAD

**Issue by timevortex** [LongSoft/UEFITool#40]
Looking at some Lenovo UEFI BIOS (downloaded from Lenovo's website) I get the following:
parseVolume: unknown file system FFF12B8D-7696-4C8B-A985-2747075B4F50
parseVolume: unknown file system 00504624-8A59-4EEB-BD0F-6B36E96128E0

Digging into these I have found credible references for both of these:
1) FFF12B8D-7696-4C8B-A985-2747075B4F50 is "EFI_SYSTEM_NV_DATA_FV_GUID" according to edk: https://github.com/tianocore/edk/blob/master/Foundation/Guid/SystemNvDataGuid/SystemNvDataGuid.h#L26

2) 00504624-8A59-4EEB-BD0F-6B36E96128E0 is "ADDITIONAL_NV_STORE_GUID" according to chipsec: https://github.com/chipsec/chipsec/blob/master/source/tool/chipsec/hal/uefi_platform.py#L512

Both of these seem to be used for storing NV ram settings.

Please include these GUID translations in the next update =)

**Comment by NikolajSchlej** [comment]
It's not the GUIDs that are unknown, but the file system of that volumes. Actually, I do know how they work but now I don't have any plans to support NVRAM editing in UEFITool - too many other things to do already.
