### ISSUE TITLE
UEFIPatch no longer fixes Ami Aptio capsule signature for bios modification for C422 chipset based Asus mainboards.

### ISSUE THREAD

**Issue by karakarga07** [LongSoft/UEFITool#402]
Hi,
UEFIPatch needs a new version for newer mainboards for modified bios updates. I can not manage to update bios on Asus Pro WS C422-ACE and WS C422 Pro/SE mainboards.

Version 0.27 was replacing 6 files and 0.28 is replacing 8 files. But currently they both are not successful.

**Comment by NikolajSchlej** [comment]
It never fixed any signatures before, and the old engine is not supported, so no updates to it will be made.
