### ISSUE TITLE
typo in guid's description.

### ISSUE THREAD

**Issue by john-8998** [LongSoft/UEFITool#403]
It should be "separator" instead of "seperator".

**Comment by NikolajSchlej** [comment]
Can you be more specific? I can not find that typo.

**Comment by john-8998** [comment]
In the guids.csv file.

**Comment by NikolajSchlej** [comment]
That file is currently being generated by LVFS service, so any typos in it are coming from BIOS OEMs. We could fix it here, but then the very next update of the file will revert the fix, so we'll have to fix it time and time again. I prefer this typo to be ignored instead.
