### ISSUE TITLE
UEFIFind cannot find text pattern

### ISSUE THREAD

**Issue by platomav** [LongSoft/UEFITool#404]
Hello,

At the attached Apple UEFI image, I am trying to detect the following pattern:

`244942494F534924................................2E00............2E00................2E00............2E00........................................0000`

This pattern should exist under two duplicate GUIDs "C3E36D09-8294-4B97-A857-D5288FE33E28".

![](https://github.com/user-attachments/assets/16610d00-33e5-4534-a03c-e0c7b3f5976c)

Checking the raw body, I can see that it is indeed 0x4A (same size as the pattern) and I can trace it from the start to the end (two 0x00 bytes). However, UEFIFind cannot find it for some reason. If I remove one null byte at the end, it finds it, though:

![](https://github.com/user-attachments/assets/b8d8f0da-1718-4baa-82ba-e418a9a158eb)

Just a wild guess, could it be something new line related? Or am I doing something wrong?

[MBA11_00BB_03B_LOCKED.zip](https://github.com/user-attachments/files/17317648/MBA11_00BB_03B_LOCKED.zip)

**Comment by vit9696** [comment]
I should have fixed this in master, please check that the latest build works fine.

**Comment by platomav** [comment]
Yes, it works now! I downloaded the win64 artifact, and it produced the expected output:

![](https://github.com/user-attachments/assets/cccd231b-3009-4d8b-b31d-c59afd0a44ef)

Maybe this can be part of a release with a version increase so that other people can download it as a dependency.

Thanks for the quick fix @vit9696 💯
