### ISSUE TITLE
False flag, I think?

### ISSUE THREAD

**Issue by affxct** [LongSoft/UEFITool#405]
![Screenshot 2024-10-10 000752](https://github.com/user-attachments/assets/96607709-3445-4da4-a390-e4838739022f)

An acquaintance of mine linked me the tool on Discord via a 7Z file, which ended up being flagged by Windows Defender through Edge - thereby preventing the download. He linked me the GitHub page for the direct download so I grabbed the zip. Once extracted, Defender flagged it for the same trojan again. I pasted the copy link for the zip in VirusTotal and one third party identified it as malicious. I assume this is a false flag, but I just wanted to bring it to your attention.

**Comment by NikolajSchlej** [comment]
Thanks, but it is indeed a false flag. You can build the tool from sources, if you want to get a proven-to-be-clean executable.
