### ISSUE TITLE
Any alternative for replacing?

### ISSUE THREAD

**Issue by 0x309f** [LongSoft/UEFITool#407]
Hello. I have a Gigabyte b550m, and I wanna replace AmiTpm20PlatformPei. The problem is it’s not showing up in the old engine, and the new obviously doesn’t allow replacing.

I’ve seen you guys suggest to use PhoenixTool, but when I try to load my bios file it says No BCPs found. Also tries MMTool which also can’t find AmiTpm20PlatformPei.

Any suggestions please? Thank you

**Comment by NikolajSchlej** [comment]
Try [Fiano](https://github.com/linuxboot/fiano), [uefi-firmware-parser](https://github.com/theopolis/uefi-firmware-parser) and [FMMT](https://github.com/tianocore/edk2/tree/master/BaseTools/Source/Python/FMMT)
