### ISSUE TITLE
The option "Replace body..." is always grayed and unavailable

### ISSUE THREAD

**Issue by SimplyLab** [LongSoft/UEFITool#42]
Hi,
I try to replace a modified PE32 image, but i only have Extract body option selectable. Replace body is gray in menu. I use 0.30.0_alpha21 of tool. The same on Mac and Windows...

Can help ?

**Comment by SimplyLab** [comment]
sorry. Bad version.

**Comment by NikolajSchlej** [comment]
No problem. The new_engine version has unfinished builder code, but much better parser, than the 0.2x ones, so I decided to provide both.
