### ISSUE TITLE
NVRAM parsing support

### ISSUE THREAD

**Issue by NikolajSchlej** [LongSoft/UEFITool#43]
- [x] NVAR entry
- [x] VSS store
- [x] VSS_standard entry
- [x] VSS_auth entry
- [x] VSS_apple entry
- [x] Fsys/Gaid store
- [x] Fsys/Gaid entry
- [x] FTW store
- [x] _FDC store
- [x] EVSA store
- [x] EVSA entry
- [x] EVSA extended data entry 
- [x] FLASH_MAP store
- [x] FLASH_MAP entry
- [x] Intel uCode
- [x] CMDB store 
- [x] OA2.0 SLIC pubkey and marker

**Comment by timevortex** [comment]
:+1:

**Comment by NikolajSchlej** [comment]
All things are done and there is no know formats anymore, so I decided to close this issue. Please create a new one, if you found something NVRAM-related.

**Comment by timevortex** [comment]
Awesome! It's looking great in uefitool and uefiextract. Thanks very much for adding all of this :)
