### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [LongSoft/UEFITool#47]
Would you like to replace more defines for constant values by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages) to stress their relationships?
* [FLASH_DENSITY_…](https://github.com/LongSoft/UEFITool/blob/19cc0312445145bbde46333bfab593e45d770da2/descriptor.h#L74)
* [IMAGE_FILE_MACHINE_…](https://github.com/LongSoft/UEFITool/blob/2ec7ce1c301a4aa9a8f52649462f0265ddd13e61/peimage.h#L36)

**Comment by NikolajSchlej** [comment]
I don't think it's necessary, just like my defines more.

**Comment by elfring** [comment]
How do you think about to support better source code debugging by the use of enumerations?
