### ISSUE TITLE
Expose FIT in Structure so UEFIExtract can extract it

### ISSUE THREAD

**Issue by timevortex** [LongSoft/UEFITool#52]
Hi,

I really like how the UEFITool UI in new_engine displays the FIT table but this information seems to get lost when I run UEFIExtract on the same flash image. Can you please look at exposing this within the structure so it will get extracted out to disk with UEFIExtract?

I've attached a screenshot here. As you can see in this example, the FIT table physical address show that it's within the Padding area. When I extract this out, I just get body.bin and info.txt for the Padding area volume and the details of the FIT table aren't exported out in any manner.

Cheers,
Parth

![screenshot from 2016-05-18 13 44 49](https://cloud.githubusercontent.com/assets/9387602/15346808/cd232ca8-1cfe-11e6-9673-6a519270282d.png)

**Comment by NikolajSchlej** [comment]
Will do. The focus for UE now is to remove dependency from Qt, so please don't expect this change to be done tomorrow, but it's rather easy change and will be done eventually.

**Comment by timevortex** [comment]
No worries :+1:

**Comment by NikolajSchlej** [comment]
Done. Is it OK for FIT to be shown to stdout instead of a file?

**Comment by NikolajSchlej** [comment]
I thinks it's fine to have it this way after all.
