### ISSUE TITLE
Fuction doesn't work right

### ISSUE THREAD

**Issue by wiliamding** [LongSoft/UEFITool#54]
I can just use Extract facility，any else si black and can't use.  what the problem

**Comment by NikolajSchlej** [comment]
Please provide more information. What is your OS, what are you trying to use besides UEFIExtract, are you compiling it yourself or using released binaries?
It works for everyone else, so the problem is probably on your side after all.

**Comment by NikolajSchlej** [comment]
I finally understood what you've meant. Use UEFITool 0.21.5 instead of NE alphas, where no rebuild is done yet.
