### ISSUE TITLE
UI Enhancement request: show hex dump of selected data

### ISSUE THREAD

**Issue by skochinsky** [LongSoft/UEFITool#56]
Sometimes I just need to quickly check something in a file or an NVAR, and having to dump it to disk is a bit bothersome. Would be nice if a small window with hex dump was shown for it.

**Comment by NikolajSchlej** [comment]
Will be done soon, got enough requests to get it higher on feature list.

**Comment by NikolajSchlej** [comment]
Done in NE A31, please test and report.

**Comment by NikolajSchlej** [comment]
I think it's time to close the issue, as Hex View is already implemented and tested now.

**Comment by skochinsky** [comment]
Sorry, I missed the release it was implemented and now can't find how to invoke it.

**Comment by NikolajSchlej** [comment]
Right mouse button menu -> Hex view...
On Jul 30, 2016 7:48 PM, Igor Skochinsky <notifications@github.com> wrote:Sorry, I missed the release it was implemented and now can't find how to invoke it.

**Comment by skochinsky** [comment]
Oops, apparently I was using an old build by accident. Thanks, looks good!
