### ISSUE TITLE
new_engine FfsParser::parseIntelImage memory exhaustion

### ISSUE THREAD

**Issue by SeanBurford** [LongSoft/UEFITool#65]
The loop that starts around line 431 in commn/ffsparser.cpp that inserts additional regions for padding between the specified offset/size regions.  Unfortunately it inserts the new entry at the wrong index into the vector, creating a finite loop (it stops once memory runs out).

To fix the finite loop memory exhaustion the advance() in this code:
        // Check for padding between current and previous regions
        else if (regions[i].offset > previousRegionEnd) {
            region.offset = previousRegionEnd;
            region.length = regions[i].offset - previousRegionEnd;
            region.data = intelImage.mid(region.offset, region.length);
            region.type = getPaddingType(region.data);
            std::vector<REGION_INFO>::iterator iter = regions.begin();
            std::advance(iter, i - 1);
            regions.insert(iter, region);
should be:
            std::advance(iter, i);
since the new entry belongs just before entry i.

Additionally, there are some integer issues, eg:
 if (regions[i].offset + regions[i].length > (UINT32)intelImage.size())
would be better expressed as:
        if (regions[i].offset > (UINT32)intelImage.size() ||
            regions[i].length > (UINT32)intelImage.size() ||
            regions[i].offset + regions[i].length > (UINT32)intelImage.size())

**Comment by Cr4sh** [comment]
Fixed in NE alpha 37: https://github.com/LongSoft/UEFITool/commit/f410b0f9695aa1f6d6318810130f6d64b23050e1
