### ISSUE TITLE
any plan to support CLI interface for UEFITool in order to insert before/after stuffs, 

### ISSUE THREAD

**Issue by sbanik1107** [LongSoft/UEFITool#68]
HI NikolajSchlej,

Would like to know, if you are currently having any plan to support CLI interface for UEFITool in order to insert before/after stuffs, i do see this going to be very helpful in order to run some automated testing. 

-Subi

**Comment by Cr4sh** [comment]
Current branch of UEFITool (https://github.com/LongSoft/UEFITool/tree/new_engine) still not supporting firmware image modification at all :( When it will be done -- we will probably implement some CLI utility like UEFIDump/UEFIExtract but for image modification and rebuilt purposes.
