### ISSUE TITLE
Are UEFITool users too shy?

### ISSUE THREAD

**Issue by NikolajSchlej** [LongSoft/UEFITool#7]
It's an issue indeed, but no one can do something about it. 
I've began UEFItool's development about 10 months ago, and there are still only very few issues reported. 
Hey, users, am I achieved perfection with this peace of poor C/C++ mix or you are just too shy to report anything? :smile: 
Please go ahead, I know there are many flaws here, but I keep forgetting about them and issue tracker will help me remember.

**Comment by bumblebritches57** [comment]
I'm not entirely sure how Apple implements EFI, but according to OSDEv they "added support for HFS+" does this mean the actual volumes inside the firmware is in HFS+? if so, that would explain why Firmware.scap won't let me go deeper than the volume level, and if that is the case it would be nice if you added support for HFS+.

but, I don't really know how it works in depth, and I'm probably wrong.

**Comment by NikolajSchlej** [comment]
That "HFS+ support" means that they have HFSPlus DXE driver in firmware and try to boot an OS from HFS+ volumes, nothing to do with firmware structure. SCAP files are signed, please read more about them [here](https://trmm.net/Thunderstrike_31c3).

**Comment by bumblebritches57** [comment]
I see, thanks for the help @NikolajSchlej

**Comment by NikolajSchlej** [comment]
Time to close the issue, because it seems they aren't anymore. :)
