### ISSUE TITLE
UEFITool NE A40 and Insyde image

### ISSUE THREAD

**Issue by walkman8196** [LongSoft/UEFITool#73]
report.
I checked, UEFITool_0.21.5_win opens the image and has the ability to edit.
UEFITool NE A40 Opens the image but does not want to replace the module.

**Comment by hardboost** [comment]
https://github.com/LongSoft/UEFITool/issues/67#issuecomment-268906461

**Comment by mittar** [comment]
UEFITool_0.21.5_win is not working with new bioses. UEFITool NE looks well but without 'modify' function is completely useless. Could you please add 'modify' function and check AM4 support? Some ASRock boards have to support ECC and if there is a possibility to use these modules in bioses of other producers it will be good news.
