### ISSUE TITLE
how to remove a microcode?

### ISSUE THREAD

**Issue by ajschot** [LongSoft/UEFITool#75]
Hey i need to use UEFITool to delete a microcode from Hasswell-EP 306F2 because it is a Aptio V bios (MSI X99S SLI Krait) but i don't understand how i can do that i found 2 places where the microcodes from this processor family are only i don't understand how to remove or rename them so they will not be loaded when the machine boots

**Comment by nexus76** [comment]
meanwhile you could use MMTool v5,
https://postimg.org/image/6w2vudlv23/
