### ISSUE TITLE
Non-standard VSS

### ISSUE THREAD

**Issue by alexarda** [LongSoft/UEFITool#79]
I think the attached bios has a non-standard NVRAM structure. It will periodically crash UEFItool NE.

If it does load, it displays "invalid" under VSS. 

The NVRAM parsing support issue (https://github.com/LongSoft/UEFITool/issues/43) mentioned creating a new issue if something different was found. 

[dx79sr_.zip](https://github.com/LongSoft/UEFITool/files/1233223/dx79sr_.zip)

**Comment by matrosov** [comment]
fixed
support added at A43
