### ISSUE TITLE
UEFITool NE 40 Insyde image

### ISSUE THREAD

**Issue by remrtehno** [LongSoft/UEFITool#80]
When openning image how I can see that's done so correctly but dont active buttons "replace is" and "replace body" also "rebuild" 
I tried run with admin root, no effect. What can I do for resolve this?

**Comment by walkman8196** [comment]
[Repeat](https://github.com/LongSoft/UEFITool/issues/73)

**Comment by remrtehno** [comment]
If I understood right, the new version of UEFITool doesnt support image editing?

**Comment by walkman8196** [comment]
All right. You need to edit the old version
