### ISSUE TITLE
UEFITool Parse Problem With Asus AMI Aptio V 6Mb Bios.

### ISSUE THREAD

**Issue by Zilog80c** [LongSoft/UEFITool#81]
Hi to,
 all; when parse this bios not appers region of bios Me, Descriptor, ecc...
![bios](https://user-images.githubusercontent.com/31391699/29753428-8c97c2ba-8b71-11e7-837e-9447d8df4254.jpg)

I Search of extract Me firmware, but i don't find.
Thaks a lot.

Zilog.

**Comment by skochinsky** [comment]
It seems this contains only the BIOS region; to get the ME you'll probably need to dump the SPI chip with an external reader.

**Comment by Zilog80c** [comment]
....mmm....i don't thinks, becasue in the site of vendor there is explit write that: 
Update NV VBIOS
Update Intel ME firmware

That there is Intel Me Firmware.

Thanks a lot.
Zilog.

**Comment by skochinsky** [comment]
got a link to the update?

**Comment by Zilog80c** [comment]
Directly from support page site of Asus.

**Comment by skochinsky** [comment]
well, what is the link then?

**Comment by Zilog80c** [comment]
https://www.asus.com/Laptops/VivoBook-Pro-N552VW/HelpDesk_Download/

Select Windows 10
Section Bios. 
Version 202

**Comment by skochinsky** [comment]
Thanks for the link.

I could not find any sign of the ME firmware in that update. I suggest you to ask folks at [Win-Raid](http://www.win-raid.com/f39-Special-Intel-Management-Engine.html), maybe they can figure out where it is hidden.

**Comment by platomav** [comment]
At most laptops, ASUS gives BIOS/EC region only updates which are encapsulated. So no FD, ME, GbE etc regions. So it is as Igor said [above](https://github.com/LongSoft/UEFITool/issues/81#issuecomment-325220430).

**Comment by skochinsky** [comment]
@platomav  so the claim "Update Intel ME firmware" is false?

**Comment by platomav** [comment]
@skochinsky Technically yes, practically no. It's a matter of bad wording/translation. They could mean that the BIOS modules which communicate with the ME got updated. ASUS tends to release some "ME Update Tool" packages, when laptops need a ME firmware update, which just use FWUpdate tool. It could also be random changelogs as most of ASUS's always say "Improve system stability" even if they incorporate very big changes. It doesn't really matter, one thing is certain: there is no ME firmware inside those encapsulated BIOS/EC updates.
