### ISSUE TITLE
official A43 build does not run due to missing Qt5 libs

### ISSUE THREAD

**Issue by skochinsky** [LongSoft/UEFITool#83]
Running the latest UEFITool_NE_A43.exe produces such messages:

```
---------------------------
UEFITool_NE_A43.exe - System Error
---------------------------
The code execution cannot proceed because Qt5Widgets.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------

```
So it seems you now link to Qt libs dynamically, however this dependency is not mentioned anywhere on download page. TBH I would prefer the previous behavior of single exe with no extra dependencies.

**Comment by carlosgbr** [comment]
have the same problem on a Windows 10 Pro system Build 10586.962

**Comment by nexus76** [comment]
Microsoft Windows [Version 10.0.16299.19]
I'm getting a 0xc000007b pop-up, just doesn't launch, even though I copied 

Qt5Core.dll
Qt5Gui.dll
Qt5Widgets.dll

into the same directory

**Comment by vutung2311** [comment]
I managed to compile a working version using this guide:
https://wiki.qt.io/Building_a_static_Qt_for_Windows_using_MinGW
I leave my compiled one here in case any of you need to use it.
https://drive.google.com/file/d/0B_-DWvOWTmeZZVhIUnBJSkFFNGc/view?usp=sharing

**Comment by matrosov** [comment]
fixed

**Comment by walkman8196** [comment]
NE_A44 the same problem

**Comment by matrosov** [comment]
fixed

**Comment by matrosov** [comment]
Before making the comments like this double check you are using a recent
version of the binary. I updated the release on the morning today ;) Thank
you for the feedback!

**Comment by walkman8196** [comment]
Thanks, now works  👍
