### ISSUE TITLE
Uefi tool dont see me from bios like Apollo Lake chipset

### ISSUE THREAD

**Issue by remrtehno** [LongSoft/UEFITool#85]
[E402NA-F1.306.zip](https://github.com/LongSoft/UEFITool/files/1473808/E402NA-F1.306.zip)

[back_ok_me_dry.zip](https://github.com/LongSoft/UEFITool/files/1473810/back_ok_me_dry.zip)
There are two files for ApolloLake chipsets.  The firts file doesnt look in Uefi tools Me region, cause I dont sure that the second file is work or have me region

**Comment by NikolajSchlej** [comment]
Duplicate of #82
