### ISSUE TITLE
NVRAM parsing hp elitebook 840 g4

### ISSUE THREAD

**Issue by KingBonecrusher** [LongSoft/UEFITool#93]
Hi! 
I have an bios rom from an hp 840 g4. The nvram could not be parsed. It looks like hp uses AA553F instead of A557F for the start. Could i send you this file maybe for parsing?

**Comment by NikolajSchlej** [comment]
Link to the image file?

**Comment by KingBonecrusher** [comment]
https://ufile.io/drt4i

**Comment by NikolajSchlej** [comment]
What version are you using? Can't reproduce on A44, parsed OK.
<img width="623" alt="1" src="https://user-images.githubusercontent.com/1845688/33807400-435122ce-dd8b-11e7-8d5e-9dc04d0260b2.png">

**Comment by KingBonecrusher** [comment]
You`re correct. It was my fault. I`ve used alpha40. The alpha44 was compiled as shared library and i haven`t used it. Can i compile it as non shared executable, or is this because of position independent executable?
