### ISSUE TITLE
Code optimization/avoiding possible problem suggestion

### ISSUE THREAD

**Issue by starter48** [LongSoft/UEFITool#96]
I've found the following ugly statements in the code:
`alignment = (UINT32)pow(2.0, alignmentPower);`
Such statement are relatively slow (the power to be computed by FPU) and unreliable on some FPU implementations due to truncation error of inexact value. For example, pow() function can return inexact value 12345677.99999 instead of 12345678.0, and this value will be truncated to 12345677 instead of 12345678 respectively.
I suggest to change such statements to pure integer math:
`alignment = 1UL << alignmentPower;`
I.e. just shift **1** left by exponent of power.
Note: here **alignmentPower** must be an integer in range [0..31] (you may use **1ULL** if not enough). I see the exponent argument always satisfy this requirement in this project.

**Comment by matrosov** [comment]
fixed in A45 and 0.22.0

**Comment by starter48** [comment]
Yet another line in ffsengine.cpp:
`alignment = (UINT32)pow(2.0, (int)(volumeHeader->Attributes & EFI_FVB2_ALIGNMENT) >> 16);`
